// let captionStructures = [
//         ["So I do some", "product", "which is also", "adjective"],
//         ["product", "is really good for the rejuvenation of your", "bodypart"],
//         ["I've been using", "brand", "since I was 21"],
//         ["Honey, it is giving", "adjective", "bodypart"],
//         ["I'm gonna add this", "product"],
//         ["I love the", "brand", "product"],
//         ["I usually use this", "brand", "product"],
//         ["So I use this", "brand", "product", "where"],
//         ["brand", "product", "in a lighter shade than the other one."],
//         ["I'm gonna bake this up because I get creased up", "where"],
//         ["This cute", "brand", "product"],
//         ["Now I'm gonna go into some", "product"],
//         ["I like to keep my", "bodypart", "kind of", "adjective"],
//         ["I don't use anything on my", "bodypart", "besides", "brand"],
//         ["I'm in love with this", "brand", "product"],
//         ["I'm now going to get into my", "product", "which is", "brand"],
//         ["brand", "", "is, to me, the best", "product", "in the world."],
//         ["I love me some", "brand", "product"],
//         ["[gentle music]"],
//         ["I use", "brandproduct"],
//         ["This is the", "brand", "product"],
//         ["Okay, another favorite of mine that I also learned on set is these", "brandproduct"],
//     ];
    
    // let brandproduct = [
    //     "Cetaphil Daily Facial Cleanser",
    //     "Kiehl's Cucumber Herbal Toner",
    //     "Peter Thomas Roth Eye Gel Patches",
    //     "Purpl and Prosper Calm Complexion Serum"
    // ]
    
    // let brand = [
    //     "Tatcha",
    //     "Laura Mercier",
    //     "Tom Ford",
    //     "Armani Luminous",
    //     "Chanel",
    //     "Anastasia",
    //     "Nars",
    //     "Fenty Beauty",
    //     "Fenty Beauty Pro",
    // ];
    
    // let product = [
    //     "serum",
    //     "under eye brightening turmeric eye cream",
    //     "lip mask",
    //     "tinted moisturizer",
    //     "color correcting pen",
    //     "concealer",
    //     "bronzer",
    //     "blush",
    //     "mascara",
    //     "lip scrubber"
    // ];
    
    // let shade = [
    //     "Torrid",
    //     "Hypnose Drama"
    // ]
    
    // let adjective = [
    //     "all-natural",
    //     "soft",
    // ]
    
    // let bodypart = [
    //     "skin",
    //     "eyebrows"
    // ]
    
    // let where = [
    //     "under my eyes",
    //     "under here"
    // ]

    // let commentsArchive = [
//     "It’s refreshing to see a celebrity be so transparent with their skin issues, makes my sensitive skin and I feel better",
//     "she’s the type of girl who just uses mascara and lipgloss and would still look like a godess",
//     "I love how her products are affordable & genuinely she’s using. Not using the luxurious brands like other celebs does !!",
//     "As an esthetician It makes me so happy to know she cares so much about her skin and makes sure she applies everything before makeup  skin care and makeup go hand in hand and she seems to know her skin. So cute",
//     "her feeling proud of herself after doing her eyeliner in just one eye totally melts my heart like she's so cute",
//     "I like how she uses the minimum product possible…because you can really tell that she’s doing it for her skin.",
//     "its weird to hear her talk ab having insecurities because to me she is the personification of the beauty standard",
//     "i love how she doesnt use all these high end make up brands. she is super relatable and seems so down to earth. love her",
//     "What a likeable person she is! No wonder she’s so loved by so many.",
//     "Finally a celebrity who is not a tiktoker.",
//     "She literally looks the same with and without make up. It just enhances her natural look she is so pretty.",
//     "I love how her net worth is like +$20million and she’s using affordable brands, and then the “celebrities” and tiktokers are using these crazy high end, expensive brands",
//     "I couldn't help noticing her crooked tooth and how it makes her look even more beautiful as she maintains her naturalness. What woman !!!",
//     "she's just so down-to-earth and that's what makes her deserve all the love.",
//     "I love how modest she is. It's so rare among celebrities and she has it naturally. Some other celebrities try to be modest but you can tell they're forcing it. I don't sense it with her. She's great.",
//     "But why is no one talking about how she’s using AFFORDABLE products and how AUTHENTIC she is QUEEN🧚🏻‍♀️🦋💫❤️",
//     "I’ve always liked her personality. She’s always been consistently real and humble/down to earth. It’s nice watching her 😂",
//     "This is what makeup is supposed to be. Enhancing your looks, not masking and changing them",
//     "Her reminder at the end that she doesn’t always put on make up and do her skin care everyday is really sweet and makes girls that look up to her don’t feel bad about themselves",
//     "i love how her products are affordable and realistic, also thank her for mentioning that she’s a person and she doesn’t look like this everyday 💚",
//     "she's the first artist whose products we can actually afford. i also like her personality and the way she talks. dhe's very natural and candid and confident.",
//     "I love the fact she is a model for most of the high luxury brands but she just choose affordable brands to show. She is just adorable inside and outside.",
//     "Her daughter is so blessed to have a mom like her.",
//     "This is probably one of my fav vogue makeup videos tbh she’s so real",
//     "She's such a kind and genuine person, that's why I've always loved her",
//     "This is REAL BEAUTY. Inside out. Just see how beautiful she looks without makeup and she hasn't done anything to her face. And she is so humble. I felt so confident and good after watching this video. She is like a girl next door. Love her!❤️",
//     "Her ending note made me tear up she's so humble and realistic I love her",
//     "There's usually so many celebrities who you can tell act so phony on these videos, but her little ending seemed so sweet and sincere ❤",
//     "She actually seems really down to earth and we love a drugstore makeup queen!!!",
//     "I love her, she is very pure and transmits a very good vibe, I loved the message she transmits, very proud to follow her.",
//     "THE MOST HONEST SKINCARE SHARED BY ANY CELEBRITY😍❤",
//     "she’s accepting, she’s hardworking, she’s relatable, she’s a mum trying her best❤️SHE IS A ROLE MODEL beautiful inside and out",
//     "the fact that she's not using high end brands makes me love her more",
//     "i love how realistic and relaxed she is while talking on camera. she’s so beautiful !!!",
//     "True to the soul ❤️..... I love how she uses all affordable and natural ways to treat her skin unlike those celebs who try show their wealth by flaunting expensive products 😒",
//     "She’s literally the sweetest, all the words she said at the end is just pure. I love her so much🤍!.",
//     "The fact that she’s uses drugstore products over high end products, we have no choice but to stan this queen",
//     "Is it only me who finds her voice relaxing ?",
//     "When she started talking at the end,I started crying. She is literally so sweet.",
//     "BEAUTIFUL! Finally a REAL person. Who doesn’t pretend to come on make up free. Stunningly beautiful with or without makeup",
//     "She has this wonderful glow now. I just love it!",
//     "She is literally looking the same before and after makeup. Such a beautifully natural & glowing skin she has ❤",
//     "she makes me feel so normal about my chubby baby cheeks 🙈",
//     "I have watched this more than 50 times now. This is my fave vogue makeup video! Bible.",
//     "I love how she doesnt cake her face or over do it . not saying it's bad when women play around with makeup or do whatever they wish but she uses it to emphasize her already gorgeous features.",
//     "She seems like such a humble person and love that she’s not using super expensive designer make up only.",
//     "I love the fact she’s not pretentious and uses drugstore cosmetics. 🙌🖤✨🤘",
//     "She's so humble. I Love it 💝",
//     "What? What kind of super model who tell the viewers that we have to appreciate ourselves?! So kind of her!❤️",
//     "I love how she is not trying to be perfect or professional. Like she puts toothpaste on pimples or lipbalm on her eyebrows. Just stuff everybody has done. I love it !",
//     "She has natural beauty 😍....and the way she explains everything is just amazing..... she's soo cute😘",
//     "Absolutely beautiful ❤️❤️❤️❤️ I hope she's still living her best life and happy ❤️❤️❤️❤️",
//     "What a sweetheart! No ego and so down to earth. St Ives apricot scrub, haha! Love her 🙂",
//     "How you can’t love her ? 🌺",
//     "So nice and humble, I love her! 💖",
//     "NATURAL BEAUTY!! 👏🏻👏🏻👏🏻👏🏻👏🏻🥰",
//     "i love her voice she is just such an adorable human, seems to love her friends and family and have a passion for her job. What a sweetheart <3",
//     "I love love love her, she is such a good and kind woman",
//     "I like that she used a lot of affordable products. And she seemed likeable and somewhat down to earth (at least for a celebrity).",
//     "She seems very genuine love her x",
//     "She seems to be down to the earth ans humble person who does not emphasize too much to be skinny nor be certain-self, which is amazing.",
//     "I love how she’s so down to earth 😍",
//     "I love how her face is just normal, like, not overly sculptured and defined like most models.",
//     "I love her vibe and the way she talks. Very  warm, nice feeling looking at her. She very sweet",
//     "There's just something about her that's so humble",
//     "These are the type of people we need on vogue instead of tiktokers...",
//     "Wow she just radiates kindness and seems like such a sweet girl💗",
//     "You’re surprisingly down to earth, lovely, sincere, relatable and beautiful! I will do my makeup today and try to look and feel pretty. I enjoyed watching this video. Thank you.💖",
//     "She's beautiful more than before makeup🖤",
//     "She seems very down to earth ❤️",
//     "She really down to earth and recognises privilege unlike some others who pretend there's no such thing. We stan a QUEEN!",
//     "Totally enjoyed your makeup tutorial! You are such a natural beauty and so sweet!",
//     "Oh my, she not only looks like an angel, she is an angel! Such a good vibes",
//     "feels like she's the only model that is actually a normal person, her features is not strong she also has a soft and young impression that makes her so unique, despite million millions of money she's receiving, she choose to  be practical, it's so nice.",
//     "She forgot to apply mascara but i think she looks good without makeup because she is really beautiful her skin tone is like a peach color amazing",
//     "Such a unique personality Best of bests ❤️",
//     "People like her with naturally clear skin are so lucky bc there’s no way someone like me with acne prone skin could ever put toothpaste or use the st ives apricot scrub 😖",
//     "the beauty this woman portrays is insane.",
//     "I love this woman, she is so authentic",
//     "I love this girl omg! She's so sweet and natural beauty :)✨❤️",
//     "she literally emphasises on self love respect omg <33",
//     "Her make up look so clean and natural idk but i love it♡",
//     "she's so humble and nice. I'm starting liking her 😍",
//     "Celebrities showing us that they are imperfect too makes me happy because they give me courage and make me feel good about myself.",
//     "I really respect how she’s not showing herself use a ton of boujee, expensive makeup products.. instead she’s showing drugstore products.. we can afford.",
//     "Can’t believe people hated her for literally no reason",
//     "I love how honest she is🥰🤩",
//     "I came to this video to gain some energy for the rest of the day, but I relaxed instead cause she turned out to be so calming 😊😂🙏🏻",
//     "Love how she doesn’t have a perfectly chiselled face and it’s rounder and more realistic; makes me feel better that i don’t have a perfect jawline",
//     "Just love the makeup 💄 tutorial. Awesome  loving the way you apply your makeup  thanks 😘  !!!!",
//     "I love her humbleness",
//     "Omgee I love the affordable make up she uses!! 💯💕",
//     "I never know her personality or listen to her voice until today. She’s really a natural and humble person 😍",
// ];

// 


/* 💋 Maya's Beauty Secrets Captions rules
  - Full sentences only
  - Sentences with brand name
  - [music/audio descriptions]
  - Sentences with a type of product discussed
  - [] Fix issue with set timeout freaking out
  - [] Remove comment/caption once it's written, then restart once have shown all of them
  + DONE
  - [x] Separate caption and comment modes, don't need to be intertwined
  - [x] Find warmer color for background
  - [x] Key pressed to toggle between views
  - [x] Finalize color of the text
  - [x] Fix height of comment section so doesn't go off screen
*/

// let captions = [
//     "Purple and Prosper Calm Complexion Serum.",
//     "I love the Tatcha lip mask.",
//     "Lancome Hypnose Drama is, to me, the best mascara in the world.",
//     "I start with the Glossier Boy Brow in Brown.",
//     "This is Pillow Talk Charlotte Tilbury, and it literally looks good on everyone.",
//     "Now for the neck it's called Neckdifirm.",
//     "The Anastasia Dewy Set.",
//     "This is a Touche Eclat concealer, which I really like.",
//     "This is a Make Up For Ever pencil."
// ]


// let brands = [
//     "Beauty Counter Blush Stick in Caramel.",
//     "I’m gonna take my Item Concealer.",
//     "My KKW Beauty Bronze and Shine Palette.",
//     "So I used a brand called Oliveda",
//     "It is our GOOPGLOW Microderm Instant Glow Exfoliator.",
//     "laura mercier this one’s really good",
//     "So first step, this YSL beauty touche eclat.",
//     "and I’m gonna use this Gucci mascara.",
//     "i’m gonna use the dior lip maximizer",
//     "There’s a special one called Stiletto Cream.",
//     "This is the Glossier Sky Wash.",
//     "I found this Kosas bronzer at Sephora.",
//     "I use this Glacier Water Hyaluronic Acid Serum.",
//     "I’m using this Glossier one.",
//     "Laura Mercier, another classic, all time favorite.",
//     "I use the Tatcha Rice Wash",
//     "I use this Dior quad.",
//     "The Osea Sea vitamin boost.",
//     "I like Lush’s stuff ’cause it’s more natural.",
//     "This is just a MAC black gel liner.",
//     "It’s called Good Genes",
//     "Gucci Envy Me.", // Samara Weavings
//     "This is the bronzer, Bobbi Brown.",
//     "Biologique Recherche.",
//     "This is the Anastasia Clear Brow Gel.",
//     "This is the Chanel blush.",
//     "I really like kind of more matte products.",
//     "This is a Benefit bronzer.",
//     "Charlotte Tilbury pencil.",
//     "This is a JILLIAN DEMPSEY Lid Tint",
//     "This is a Kosas concealer",
//     "This is a Sisley Primer of sorts.",
//     "This is, ISDIN Actinica.",
//     "Next I’m gonna use the Hydrocodone serum from iS Clinical.",
//     "Elizabeth Arden, Eight Hour Cream.",
//     "What I’m gonna start with is Clinical Firming Copper Mist.",
//     "In the shower, I use Living proof, Perfect Hair Day In-Shower Styler.",
//     "I’ll put on this COOLA Organic lip oil.",
//     "I use this Chantecaille Anti Fatigue Correction Pin.",
//     "I’m gonna use Kate Somerville’s KateCeuticals Total Repair Cream.",
//     "I’m using the Kate Somerville KateCeuticals Lifting Eye Cream.",
//     "and the one that I love is this MARA Universal Face Oil.",
//     "Here is the NuFACE, my favorite little thing.",
//     "Next, what I do is I use my NuFACE",
//     "I’ll use Kate Somerville’s ExfoliKate, the body version.",
//     "I’ll use this Kate Somerville ExfoliKate.",
//     "I have this Organic Pharmacy Carrot Butter Cleanser.",
//     "this urban decay blue eyeliner",
//     "this laura mercier number six",
//     "i use nars",
//     "this dior show eyebrow pencil",
//     "i really love this armani luminous silk",
//     "i use this laura mercier primer",
//     "i use christine chin cleanser",
//     "This one’s Pure energy.",
//     "We’re gonna use Ilia and just do some mascara.",
//     "So I just have a Charlotte Tilbury lipstick",
//     "I have this product, which is from Urban Decay.",
//     "the Glossier Pro Tip.",
//     "I will start with eyeliner, Charlotte Tilbury.",
//     "So I’m gonna use a little bit of this Laura Mercier powder.",
//     "I just use this little Glossier Cloud Paint.",
//     "I really, really love the Fenty Beauty Soft Matte Longwear Foundation.",
//     "I’ve got this really great one from Ilia.",
//     "This is the Kosas Cloud Set powder.",
//     "with the Tom Ford Shade and Illuminate palette",
//     "This is the Dior Backstage Rosy Glow powder blush.",
//     "I’ve talked about this Makeup Forever palette before.",
//     "MAC Extended Play Gigablack Lash.",
//     "This is the Anastasia clear eyebrow gel.",
//     "This is the color Perfect Storm.",
//     "This is the Kylie Cosmetics Stormi palette.",
//     "This is Ariana Grande’s brand",
//     "The base that I’m using for the eye is REM Beauty.",
//     "This is the Kosas concealer.",
//     "I love the Chanel Vital Lumiere.",
//     "the Dieux Forever Eye Mask.",
//     "Barrier restore cream, this specifically we call our peptide powerhouse.",
//     "Next I’m gonna go in with the Rhode peptide glazing fluid.",
//     "I’m gonna start with this Environ moisturizing toner.",
//     "This is YSL 24.",
//     "It is called Nipple Balm.",
//     "This is one that I use from Authentic Beauty Concept.",
//     "CeraVe moisturizing cream.",
//     "CeraVe hydrating facial cleanser.",
//     "I got it from Target for like $10.",
//     "I’m gonna use Burt’s Bees.",
//     "And so there’s a certain nostalgia that comes with Benefit makeup for me.",
//     "So I’m gonna use this Benefit product, High Beam",
//     "I’m going for Marc Jacobs.",
//     "I use the Dr. Hauschka Eye Definer number two.",
//     "So I’m gonna use the Charlotte Tilbury Desert Haze palette.",
//     "It’s called ONE/SIZE BrowKiki.",
//     "It’s the Benefit Dandelion.",
//     "It’s Light Plus Mineralize Skinfinish",
//     "I’m gonna use this, MAC.",
//     "I’m gonna go for this Charlotte Tilbury",
//     "It’s so good, the coverage is amazing. Laura Mercier.",
//     "I’m just gonna do a little Aquaphor.",
//     "So I’m gonna do my moisturizer, which is Lamer.",
//     "I take this Rejuvi Flavonoid Complex,",
//     "Number one. Rejuvi.",
//     "Here’s my fragrance, Eilish",
//     "It’s so amazing, Laura Mercier, it is so nice.",
//     "I take the love of my life, which is Aquaphor Healing Ointment",
//     "I use a lot of Olaplex products for my hair.",
//     "But what I like to do at night is use this Olaplex Number 6.",
//     "from Biba, this is her cream barrier.",
//     "I’m gonna go back in with the Fenty palette",
//     "My YSL Mascara.",
//     "I actually use two different shades by Dior.",
//     "I’m gonna go in with my YSL Concealer.",
//     "I’m gonna go in with my Fenty Powder.",
//     "I’ll use my Dior, right here.",
//     "Fenty Translucent Powder.",
//     "I like to use my Anastasia Brown Pencil because it gives natural strokes.",
//     "I’m going to apply my Pro Heal Serum.",
//     "This is my favorite cleanser by Is Clinical.",
//     "I use this Dior beauty palette.",
//     "I use the Chanel mascara.",
//     "I have used the Nars Orgasm color forever.",
//     "Chanel eyeliner.",
//     "I use this Chanel Essentiel stick.",
//     "I use the Benefit Gimmie Brow.",
//     "So I use Supergoop Unseen Suncreen.",
//     "I love this Tata Harper resurfacing mask.",
//     "For moisturizer, I use Whipped Dream by Isla.",
//     "For an exfoliator, I used Pharrel’s Humanrace skincare.",
//     "I use Kiel’s, super simple and most important for my life.",
//     "It’s tinted from Fenty Beauty.",
//     "We’re gonna go with Milk.",
//     "Next blush, Tata Harper.",
//     "Charlotte Tilbury blush.",
//     "Urban Decay, just the darkest shade.",
//     "Really quickly, we’re gonna go in with this KVD eyeshadow primer.",
//     "Brow gel time, this is from Kosas.",
//     "NARS concealer, this is the go-to brown girl concealer I think ’cause it just gives you great coverage.",
//     "This one is from Armani.",
//     "This one is from PÜR.",
//     "So we got Milk over here with their Hydro Primer.",
//     "I just use a face wipe, also from Epicutis.",
//     "You got this serum from Epicutis, a little goes a long way.",
//     "As a last step, Fix+.",
//     "So now I’m gonna go for the highlight, and I’m using Charlie Tilbury’s little duo.",
//     "It’s Push Up Lashes by Charlotte Tilbury.",
//     "Charlotte Tilbury.",
//     "Space Cowboy, Urban Decay.",
//     "I remember like with the first makeup item, that I like saved my pocket money on, and was obsessed with, was this Dior cream eyeshadow ring.",
//     "I’m gonna use Fix+ by MAC.",
//     "It’s the Dior Skin Glow.",
//     "This is Glow Recipe.",
//     "It’s by MDNA Skin, and obviously, Madonna knows what she’s doing, ’cause she looks amazing.",
//     "Kiehl’s Ultra Facial Cream, also just something that’s never broken me out.",
//     "This avocado eye cream by Kiehl’s, was one of the first eye creams I think I bought.",
//     "This is called the Glow Stick.",
//     "This is from Supergoop!",
//     "I’m just gonna go in with this Charlotte Tilbury lip liner.",
//     "I’m gonna go in with this Tarte Chrome eyeshadow pot.",
//     "Then I’m gonna go in and curl, and then I’ll use this Hourglass mascara.",
//     "I’m gonna go in with this Charlotte Tilbury liquid eye pencil.",
//     "I love brands like Innisfree, I think they’re great.",
//     "It’s just the göt2b glued gel.",
//     "This is the Hourglass warm brunette pencil.",
//     "I’m using the Fenty setting powder.",
//     "I use the Charlotte Tilbury lip and cheek, and then this Drunk Elephant Bronzer.",
//     "Underneath this place is Dior Foundation.",
//     "So I start with the Charlotte Tilbury Wonder Glow.",
//     "La Mer under eye Balm, and I’ll just take a little bit on my finger.",
//     "First step, I use my Curology cleanser.",
//     "I will have a spray of Sacred Mist.",
//     "It is Sam McKnight’s hair product, Cool Girl, which he said he made for me, ’cause my hair was always a little bit shabby looking.",
//     "So now I’d use the Golden Nectar.",
//     "This is Leneige.",
//     "Anyway, I’ve been doing the Cosmoss moisturizer, and it’s made from oakmoss as well with CBD.",
//     "So this one’s from Santa Maria Novella.",
//     "It’s called Cosmoss and we have done a tea.",
//     "This one’s from & Other Stories.",
//     "This is Oribe’s Gold Lust Hair Oil.",
//     "This is Freck.",
//     "Burt’s Bees chapstick.",
//     "I line my lips with this MAKE UP FOR EVER Aqua Lip Pencil.",
//     "I’m using this Kosas Breezy Cloud Set Powder.",
//     "It’s by Stila Stay All Day Waterproof Liquid Eye Liner.",
//     "HUDA BEAUTY Palette, I put a little Sanrio sticker on there.",
//     "Urban Decay Eyeshadow Primer Potion.",
//     "So I use this Hourglass pencil.",
//     "I use Sunnies Face.",
//     "This is the Charlotte Tilbury Beauty Light Wand.",
//     "I use this bronzer stick from Westman Atelier.",
//     "This is Summer Fridays CC Me Serum.",
//     "I’m gonna go in with some eye patches from Peter Thomas Roth.",
//     "The ingredients are super simple and I put it on this vibrating cleansing pad from FOREO.",
//     "This one’s from Farmacy.",
//     "Got the R&C fragrance.",
//     "Now what I’m doing is I’m highlighting my cheeks, so I have the iconic London blush and highlight palette.",
//     "I’ma do Makeup by Mario Bronzer.",
//     "All right, so now it’s time to seal the deal with the Danessa Myricks powder.",
//     "I have my Nyx palette right here.",
//     "I use this Yummy Skin Danessa Myricks face toner.",
//     "I have to use my girl Lala, her Inala Hair Power Potion for the edges.",
//     "So I use the Murad SPF 45 on the skin.",
//     "OAM Radiance Moisturizer.",
//     "Face mask by 111SKIN.",
//     "I am sharing with you guys for the first time my skincare line, OAM Skin, which stands for On A Mission.",
//     "So what I use is the Got2B Glue Gel, and I love this because it secures the eyebrows.",
//     "And I use this edge control called Truth by Tasala.",
//     "I’m going to use a Mac lip liner, which is called Nightmoth.",
//     "I have my very own lipstick from Mac.",
//     "This is Makeup Forever.",
//     "I add a little blush and I use NARS.",
//     "I also love this highlighter from Fenty.",
//     "This Dark Deep Mineralizer from Mac.",
//     "Laura Mercier and I use this to bake",
//     "Purple and Prosper Calm Complexion Serum.",
//     "I use Aqua Forte.",
//     "Dermalogica exfoliator",
//     "I’m going to use the Face Gym.",
//     "This is the Youth To The People one.",
//     "Probably one of my favorite parts of my skincare routine is my Laneige lip mask.",
//     "My skincare routine is not complete without some Cosmoss.",
//     "Glossier Stretch Concealer, which again is scratched and very much used.",
//     "Nars Creamy Concealer.",
//     "I use the Charlotte Tilbury Contour Wand.",
//     "For the eyes, I use Charlotte Tilbury.",
//     "Charlotte Tilbury highlighter.",
//     "A Lancome mascara.",
//     "The Beverly Hills Anastasia Clear Brow Gel.",
//     "Pillow Talk by Charlotte Tilbury, a classic.",
//     "And then we’re going to use the Fenty Beauty lip gloss.",
//     "Clear Cell cleanser.",
//     "The next thing I’m using right now is this thing called Age Intervention Peptide Extreme.",
//     "The Tom Ford Illuminating Primer.",
//     "It’s the Lineage sleeping mask.",
//     "This is the Westman Atelier Foundation stick.",
//     "This is the Nars Creamy concealer.",
//     "This is also Westman Atelier and it’s the bronzer contour.",
//     "This Tower 28 is an all time favorite",
//     "And then Glossier Cloud Paint, another classic.",
//     "I’m gonna use a tiny bit of the Cloud Paint.",
//     "It’s Chanel, it’s really great.",
//     "This is a Cover Girl eye pencil.",
//     "This is Surratt.",
//     "This is the Pillow Talk in medium.",
//     "This Glossier lip and the shade Trench which is the one that I’m super into right now.",
//     "I used the Anastasia Brow Freeze.",
//     "This is called Freck.",
//     "So my next step is a serum from Obagi.",
//     "And I finish it off with a Tata Harper Spring Mist.",
//     "I use this Huda Beauty eyebrow pencil.",
//     "I use a daily cleanser from Vanity Planet.",
//     "I like that, I like that.",
//     "[blows kiss]",
//     "I have it in like three colors",
//     "This is my Dior palette",
//     "It's my favorite, favorite, favorite, favorite palette.",
//     "I like to do a little ice cube facial.",
//     "it's honestly been so therapeutic",
// ]

// let captions = nonBrands;

// let captions = documentationCaptions;
