let captions = [
    "[mellow music]",
    "This is a cleanser that I use.",
    "A Black woman owns this company and it’s non-toxic.",
    "The back says, \“I like my products how I like my people, non-toxic.\”",
    "I’ve always been very serious about washing my face.",
    "So I do some toner, which is also all-natural.",
    "I have sensitive skin so I try not to do too much.",
    "I don’t need a lot of harsh chemicals.",
    "Rub it in like this.",
    "You can do some deep breathing.",
    "Also a woman owns this",
    "It’s skin products that actually understand what’s going on with my skin.",
    "Therabody for my face and I use the red light.",
    "Red light is really good for the rejuvenation of your cells",
    "I’ve been using Lamier since I was 21.",
    "This is a soft cream, so you don’t have to make it warm.",
    "This is also good for being on the go.",
    "Honey, it is giving moisturized skin.",
    "I’m gonna add this under eye brightening turmeric eye cream.",
    "I don’t always have time to do this routine.",
    "A little dab like that.",
    "And you know, this is also very therapeutic.",
    "When I do have time, I’m very big with meditation.",
    "I love the Tatcha lip mask.",
    "I usually use this Laura Mercier tinted moisturizer.",
    "So I rub it in like this.",
    "Growing up, Rite Aid or CVS would be where I would buy my makeup.",
    "I have really, really dark circles because I don’t get enough sleep.",
    "Armani Luminous Concealer in a lighter shade than the other one.",
    "Live your life.",
    "Who cares what people think?",
    "Hit it up like this.",
    "I am my own best friend.",
    "Tatcha the Silk Powder.",
    "Now I’m gonna go into some bronzer.",
    "This cute Chanel bronzer.",
    "I don’t use anything on my eyebrows besides Anastasia",
    "I’m in love with this Liquid Killawatt.",
    "I’m going to now get into to my blush, which is Nars Torrid.",
    "You can do a little smile.",
    "Ooh, looks like I’m blushing.",
    "Lancome Hypnose Drama is, to me, the best mascara in the world.",
    "I love me some Fenty Beauty clear lip gloss.",
    "I wasn’t allowed to wear makeup growing up.",
    "I use Cetaphil Daily Facial Cleanser.",
    "Next in my skincare routine, I use Kiehl’s Cucumber Herbal Toner.",
    "This is the Fenty Beauty Pro lip scrubber",
    "these Peter Thomas Roth Eye Gel Patches.",
    "somehow that’s like a buzzword for me to buy it.",
    "It’s a little spa tease, you know.",
    "My next step is this Tatcha Dewy Skin Mist.",
    "I take a nice deep breath and just release everything for my day.",
    "My next step are my Skin Worship Dew Drops.",
    "These are combined of different natural oils.",
    "Next, I use this Paula’s Choice sunscreen.",
    "it’s SPF 50 which is super strong and I prefer a dewy look on my skin.",
    "it keeps me looking all glossy and shiny all day.",
    "I use the Laneige Overnight Lip Mask.",
    "I really value my skincare routine more than makeup.",
    "One, because I am not super well versed in makeup yet.",
    "My makeup routine is super simple.",
    "I start with the Glossier Boy Brow in Brown.",
    "I don’t do anything to my brows.",
    "I don’t wax them and I don’t tweeze them.",
    "Next is mascara. I use the Saie Beauty Mascara.",
    "Last step of my daily beauty routine is I use this Tom Ford Luxury Lip Gloss.",
    "It may be a bit controversial, but I like it",
    "I use this Nairobi Foaming Lotion.",
    "So this is a little mousse that I use",
    "I feel amazing and beautiful, and I hope everybody else has a great day.",
    "[gentle music]",
    "[gentle upbeat music]",
    "I love this Biologique.",
    "[gentle upbeat music continues]",
    "I do once a week, this Barbara Sturm Enzyme Cleanser.",
    "[gentle upbeat music continues]",
    "So now, we are going to do a mask.",
    "I keep them in the fridge if I wanna be extra fancy.",
    "[gentle upbeat music continues]",
    "And then I’ll kind of rub some of the serum down on the neck.",
    "I’ll basically put it anywhere because I’m not wasting any SK-II serum, let me tell you.",
    "If I’m feeling extra fancy, I’ll use the Joanna Czech face roller over this.",
    "[gentle upbeat music continues]",
    "What I love about this roller more than the other ones is it actually like, grabs your face.",
    "It’s not just rolling, it’s pinching, and I like to think it’s like contouring and defining.",
    "So next, thank you mother for the best advice, La Mer Eye Cream.",
    "I love this one because it’s just so silky, velvety.",
    "I go up under the brow. I know some people do, some people don’t.",
    "And I use my ring finger because it’s the lightest touch.",
    "the skin around your eyes is the first to go.",
    "the finale for this is my favorite Charlotte Tilbury Magic Cream.",
    "So not only do I love her products but I love her.",
    "And she taught me about going like this",
    "[gentle upbeat music continues]",
    "Like, I love researching new products",
    "My loyalty lies with Barbara Sturm for her Sun Drops.",
    "So I’m very, very loyal to my sunscreens.",
    "I suffer from the worst chapped lips",
    "[gentle upbeat music continues]",
    "we are going to do mom’s night out makeup.",
    "I suffer from dark circles.",
    "And so I’m all about, how can I fix that? [chuckles]",
    "And so for me, I’m trying every under eye patch under the sun.",
    "The Wander Beauty ones have really stood the test of time.",
    "[gentle upbeat music continues]",
    "And then we’re going to prep the skin with a little oil.",
    "I personally love a face oil. I know it’s controversial.",
    "I love, especially this one under makeup.",
    "I feel like it just gives you that little extra glow.",
    "so I’m warming it up with my hands.",
    "And then I just kind of press.",
    "For foundation, I just do Charlotte Tilbury Light Wonder.",
    "You know, this much.",
    "I’ve had every foundation brush known to man.",
    "So I use this Charlotte Tilbury, it’s like an under-eye corrector.",
    "So I just do a little again, like ring finger, just patting.",
    "Before I do that though, I have to prep the Beauty Blender.",
    "I like this Solar Rose Water.",
    "And I just spray this. [bottle spraying]",
    "I am a real fan of the Beauty Blender.",
    "[gentle upbeat music continues]",
    "I don’t like to be too powdered because I like a little dewy look.",
    "All right, we’re gonna curl our lashes next.",
    "This is like a little Chanel peachy nude",
    "I’m gonna do blush next.",
    "And this blush I just discovered recently",
    "I’m always buying new mascara more than anything",
    "So now, we’re gonna do brows.",
    "I’m obsessed with my brows.",
    "I love to brush my brows.",
    "Iconic London makes this brow wax.",
    "And guys, it comes with a gold toothbrush.",
    "My eyebrows have their own toothbrush.",
    "[gentle upbeat music continues]",
    "I let the girls be themselves.",
    "This is Pillow Talk Charlotte Tilbury",
    "And then I’ll go back with whatever’s on my Beauty Blender.",
    "So since I’m going out tonight, I am going to do a little highlight",
    "I’m gonna throw on a little color in the crease.",
    "[gentle upbeat music continues]",
    "So we do a little dot here and a little dot here.",
    "We’re gonna highlight, we’re gonna hit it.",
    "The Anastasia Dewy Set.",
    "It feels also amazing and smells good.",
    "I love this THE WELL Reset Oil.",
    "I’m all about essential oils.",
    "It’s a little roll-on.",
    "So what I do is I rub it in my hand like this.",
    "[hands rubbing]",
    "[breathing in]",
    "Do a little breath like this.",
    "[gentle upbeat music fades]",
    "[upbeat music]",
    "So I use a pretty standard face wash, Cetaphil.",
    "So my hands are wet and I’m gonna put a little of this in my hand.",
    "My skincare routine has gotten more and more complicated.",
    "I get older [laughing]",
    "I’ve always been really careful about like, washing my skin",
    "Here’s my little exfoliating wash cloth",
    "This is called Elastascene and you put this wherever you have fine lines",
    "Just squeeze it like this into your hand.",
    "Okay, my next step is this vitamin C serum called Pro Heal",
    "this one is called antioxidant defense cream.",
    "It seems complicated, but it’s not.",
    "Two squirts, one, two, of the serum. One squirt of the cream.",
    "This entire sequence I also do at night",
    "Now for the neck.",
    "You take two pumps of this.",
    "I really love blush.",
    "that’s something that you can do that’s non-invasive",
    "Lastly, I had this amazing eye cream from Hourglass.",
    "Which I really, really love because I’m very picky about eye creams",
    "So I use this in the daytime and especially at night.",
    "I use a lot of it.",
    "I’m gonna use this tool just by Jillian Dempsey",
    "I also go underneath my eyes with this",
    "So this is my new favorite sunscreen, Biore UV.",
    "Now that my skin is prepped, we can move on to makeup.",
    "This is a really wonderful foundation by Hourglass.",
    "I use about that much.",
    "And then I apply it with this little brush.",
    "I don’t like a lot of coverage.",
    "I like to be able to see the freckles in my skin",
    "This is another Hourglass product.",
    "It’s a really great but very pigmented concealer.",
    "So where I like to use it, I use it, a little bit on my finger.",
    "My issue is always right underneath my eyes.",
    "This is also an area that used to bother me a lot",
    "So there’s not a lot I can do to control it.",
    "Now I’m gonna add just a little bit, a little bit of powder.",
    "Not too much, but just, just enough. Okay.",
    "Drawing in my eyebrows is a major, major feat for me.",
    "The brow pencil that I really, really like is from Anastasia",
    "And believe it or not, the shade that I use is blonde.",
    "I take the pencil and I start right in the middle",
    "you give yourself a little bit of balance with it and it takes forever.",
    "you can add a little bit of foundation right on the top",
    "And then I realized you can buy the stuff yourself.",
    "So right now you can see I have a little bit of color on my lashes",
    "So this is something else that I found, it’s called Living Libations.",
    "It literally makes you look like you’re blushing.",
    "I use it on my lip and I can also use it on my cheeks.",
    "And see how sheer it is on my finger?",
    "It blends really easily too.",
    "It sinks kind of right into your skin.",
    "This is another product that I use, the Olio Osso.",
    "My next step is this Laura Mercier eye pencil called Amethyst.",
    "So I like this Dior Show mascara because I like this color.",
    "you can use one of those eyelash combs",
    "So this is Hourglass’s Red Zero.",
    "This is a great red.",
    "[easy jazz music]",
    "I always like to start by setting the stage.",
    "This is Santal 26. I love this candle.",
    "It’s kind of a signature scent for me.",
    "I also like to say a little bit of an affirmation.",
    "I am in perfect health always, my family is in perfect health always.",
    "I am youthful and timeless at every age.",
    "I use the JLo Beauty Cleanser.",
    "I’ve always had a very simple skincare routine",
    "a little bit of a cream, sunscreen, very basic.",
    "Next thing I do is I put in my eyedrops.",
    "I like to have bright eyes.",
    "That JLo Glow Serum.",
    "I feel like it’s the first thing everybody sees.",
    "So you see, we kinda got a beautiful glowy skin going right now.",
    "One of my biggest beauty secrets is sleep.",
    "And so, it’s either under 4 or over 7, that’s my rule.",
    "This next step that I do is moisturizer, my day cream.",
    "But the truth is, is when you start young, it will make a huge difference.",
    "I’m gonna add a little bit of La Mer lip balm, which I really love.",
    "My next step is my JLo Beauty Eye Cream.",
    "I put eye cream a little bit here.",
    "I heard another beauty secret that I’ve lived by as well",
    "I’ve never shared this with anybody.",
    "I take some of these darker colors in here and mix them.",
    "A little bit above my cheekbone.",
    "Before I used to go right here in the cheekbone",
    "Like, look at this chin",
    "And then I take a thinner brush, like this, with some of the lighter colors.",
    "This is a Touche Eclat concealer, which I really like.",
    "And then, I brighten a little more there",
    "Now, this is not supposed to be lip liner.",
    "Then I take my Chanel Vitalumiere.",
    "I’ve used this for years as well, and I use three different shades.",
    "I used 50, 30, and I just took this off, and 20.",
    "Put a little here and 2 squirts of 30, and I take a foundation brush.",
    "Like, I love those kind of sexy, gorgeous, sireny looks.",
    "Now I’m taking this and going down the light parts of my face.",
    "I just kind of go over everything again just to blend it all in.",
    "And I start going up and down the nose.",
    "As you can see, I’m already startin’ to look glowy.",
    "It starts with your skin, and it starts with how kind of rested and happy you are.",
    "You can’t cover up how you feel on the inside, how you take care of yourself.",
    "just to define the eye just a little bit.",
    "I take the brown ’cause I like a very soft look.",
    "And I love playing with makeup, don’t get me wrong.",
    "Like, I love doing all kinds of makeup looks.",
    "You guys know that, you’ve seen me on the red carpet for years.",
    "And I just go along the top of the eye.",
    "And then, I will take a little bit of the dark, if I wanted to just kind of accent a little bit.",
    "I like cream blush, especially when you get a little older.",
    "This brand is Beautyblender, and this one is Playful Peach.",
    "So I take a little bit, again, with my foundation brush.",
    "Take the big brush and just make sure your face matches your neck.",
    "This is a Marc Jacobs highlighter that I’ve just become obsessed with.",
    "I don’t even know if this is continued anymore.",
    "See this one says, this goes in my purse.",
    "I just kind of reinforce the nose contour just a bit.",
    "Then I take that thin brush again, and I soften.",
    "So I actually learned this trick for my lips from TikTok or Instagram Reels",
    "This is a Make Up For Ever pencil.",
    "I’m obsessed, it’s my new fave.",
    "And then do the same thing, a little line right here.",
    "I really like these Fenty Beauty lip glosses, just like this peachy color.",
    "Gonna get my Anastasia pencil.",
    "We all have imperfections in our eyebrows that we have to fill in, so I’m gonna fill in.",
    "I take the finishing touch, Make Up For Ever.",
    "I forgot my mascara.",
    "This is the most important part.",
    "Now I can do a 5 minute version of this for you guys one day",
    "I have a serum, a body cream, and a booty cream.",
    "If you know, you know, and you’re obsessed.",
    "Put my serum on first.",
    "This is for cellulite, this is for dimpling, this is for stretch marks.",
    "You’re going to feel it’s gonna have a little heat to it.",
    "I love you guys.",
    "I couldn’t be more glowy right now.",
    "my life is full of joy, laughter, adventure, and love.",
    "Put it all in there [laughs].",
    "[uplifting chillstep music]",
    "[calming lo-fi music]",
    "This is my ride or die face wash, I’ve been using it since I was 13.",
    "I saw this on TikTok and I can’t remember who did the video but she used a brush to wash her face.",
    "[uplifting lo-fi music]",
    "[chuckles] that’s okay.",
    "You go in and you kind of mix it up, make it foamy.",
    "I have noticed a difference in the amount of blackheads I’ve been getting.",
    "Always pat your face dry, it retains moisture.",
    "Lotion P50 1970, I just like put a little bit on my palm.",
    "[calming lo-fi music]",
    "SkinCeuticals C E Ferulic Serum.",
    "I use this Phyto Brightening Treatment, also by SkinCeuticals.",
    "[relaxing music]",
    "I always carry around some sort of moisturizer because I hate the feeling of dry skin.",
    "I also like feeling dewy, some people would say I look sweaty, it’s just healthy skin, babe.",
    "Holy grail of moisturizers, my favorite, it’s Barbara Sturm face cream.",
    "[calming lo-fi music]",
    "Sunscreen, always, SPF 50, SPF 30 minimum.",
    "Eye serum!",
    "This one’s by clearance, it’s called the double serum.",
    "[serum pumping] [calming music]",
    "I do use strong products",
    "The Kissu Lip Mask.",
    "Before I start my makeup, my perfume, Baccarat Rouge.",
    "that’s what people smell when you’re walking away from them.",
    "You know how everybody says Rihanna smells so good? I would love to be remembered the same.",
    "First step is NARS, this is their Light Reflecting Foundation.",
    "[calming lo-fi music]",
    "Maybe that’s definitely not the right shade.",
    "When in doubt blend it out.",
    "Have I been wrong this whole time?",
    "[laughs]",
    "Oh my god, this is the absolute wrong time for this to be happening",
    "Foundation is not foundationing, just put it on your neck.",
    "for a second it was giving Oompa Loompa, now it’s giving matching.",
    "I think I’m gonna do concealer now and this concealer is pretty light.",
    "[calming chillstep music]",
    "Kat Von D Shade + Light Contour Palette, I have used this since I was 18.",
    "I’ve always found it to feel like a form of self-care.",
    "I like to button my nose.",
    "I see girls do this all the time on TikTok and I think it’s so cute.",
    "Take one of these light powders.",
    "Is that baking? [gasps] I’m baking!",
    "So next step is blush, I like to use this one",
    "Look, it’s got a little shell on it.",
    "These are incredibly tinted, right, so use sparingly.",
    "I used to hate my eyes, people called me bug-eyes, and now I really really appreciate them.",
    "Confidence is something that it comes and goes.",
    "It’s not always easy but it’s so true.",
    "It’s a form of self-care, being kind to yourself.",
    "My favorite Holy Grail.",
    "Like, hair’s expensive.",
    "Waterline Eyeliner, I use the Urban Decay 24/7.",
    "It just makes my lashes look longer and fuller and darker",
    "[calming chillstep music]",
    "This is the Benefit They’re Real! Precision... [chuckles] Precision liner.",
    "I saw this thing where you follow the line of your bottom eyelid, oh boy.",
    "[relaxing lo-fi music]",
    "We did it!",
    "A little product called Freck XL.",
    "I have little freckles that get covered up with makeup",
    "[calming chillstep music]",
    "Mascara, I really like this, this is Armani.",
    "We’re gonna do a peachy lip.",
    "I love these Hermès Lip Oils, they’re so nice and they keep your lips moisturized.",
    "I think I’m gonna mix these two but before I do that, kind of contour my lips.",
    "Now I’m gonna start with orange and we’ll see how we like it.",
    "I like that, I think that’s pretty, I’m gonna do a little bit of the pink though.",
    "Those are my beauty secrets.",
    "Love you. [kisses]",
    "[soft upbeat music]",
    "I start my skincare routine with my Barbara Sturm cleanser.",
    "[soft upbeat music]",
    "I’ve always had to have some sort of skincare routine",
    "I really love, love, love these Elemis pads.",
    "[soft upbeat music]",
    "After that, I love using my Barbara serum, Clarifying Serum.",
    "I pretend like I know what I’m doing",
    "I’ve really put my skin through a lot",
    "It’s light, but it really, really really helps keep my skin nice and moisturized.",
    "I am a huge, huge self-care person.",
    "I love it so much and smells so good and I’m addicted to it.",
    "Laneige lip mask.",
    "What also is really, really, really great with these pads is for your hands.",
    "So I exfoliate my hands with these pads.",
    "I do these like before bed.",
    "You wake up and your skin is like a baby the next day.",
    "it’s this La Mer hand cream.",
    "My first step is foundation and I love this Giorgio Armani foundation.",
    "I would focus a lot more on contouring and highlighting",
    "[soft upbeat music]",
    "Armani powder.",
    "So just, I mean, I’m kind of using a lot. I don’t want a lot of shine.",
    "I don’t really want a lot of glow.",
    "I want more of a matte coverage.",
    "I’m also making sure that I am kind of getting rid of any of the shine.",
    "I’m using my Anastasia brow pencil.",
    "I do my brows myself.",
    "This is gonna be a little bit thicker just because this is for the stage.",
    "Anastasia Clear Brow Gel just to sort of set them.",
    "Now I’m gonna take this Tom Ford bronzer.",
    "Makeup by Mario, this is their Master Mattes eye palette.",
    "I start with this really pretty sort of like pale peach color",
    "I’m mixing two darker colors here and here.",
    "This is the hardest part of the makeup for me, is the black liner.",
    "[soft upbeat music]",
    "I also have this amazing Maybelline mascara.",
    "Look at the no mascara and mascara",
    "I feel like I am in this really wonderful and incredible place in my life right now.",
    "[laughs]",
    "After everything is done, I take one really close look and I just kind of do one extra little touch up.",
    "The great Laura Mercier, I’ve been using her products for years. I love this blush so much.",
    "[soft upbeat music]",
    "I have the great Charlotte Tilbury lip liner.",
    "[soft upbeat music]",
    "Makeup Forever, and this is the Rouge Artist.",
    "[soft upbeat music]",
    "I’m gonna make myself some tea right now.",
    "[lips smack] Bye.",
    "[soft upbeat music]",
    "[gentle music]",
    "First up is this Lancer Sensitive Cleanser.",
    "Getting older, growing into your body, it’s fine.",
    "We all have breakouts, it’s okay.",
    "I’m very strict about my routines.",
    "Every morning, I make sure I wash my face.",
    "So I wake up with these bags under my eyes",
    "My next step is this Velour Lash Serum.",
    "My advice, if you wanna get better eyelashes and like strong eyelashes and keep your eyelashes, just probably refrain from extensions.",
    "So here’s my Laneige Lip Mask.",
    "Don’t forget your sunscreen",
    "Now we are ready for makeup.",
    "This is my Stoney Clover bag.",
    "My Chanel Liquid Skin Tint.",
    "ever since I saw it I was like, oh my God, I need to get it",
    "Next step, we have the Lancome Concealer.",
    "I feel like as the years have gone by, I’ve really, like, gotten my system down.",
    "And when I go to sleep, I put the little pimple patches on.",
    "I’ve had the same bronzer since eighth grade.",
    "I’m gonna show the inside of it, but oh my God, okay, I’m just saying, it’s been with me since eighth grade.",
    "Next step is this Laura Mercier Blush. Dab it in.",
    "And I normally smile so like I get the apples in my cheeks.",
    "I am obsessed with blush.",
    "This is the palette I use and this is the brush I use.",
    "But I’m using this powder rather than an eye liner, like a pencil, because I feel like I mess up too much.",
    "I’ve gotten to a point where I base my day off of if I like my eyeliner or not.",
    "My eyeshadow. One of Kylie’s palettes.",
    "I love, like, a good rosy eyeshadow.",
    "I go in with a little beauty blender.",
    "Eyelash curler.",
    "I put on mascara on the lengthy part of my eyelashes rather than the base.",
    "I’ve literally been watching Vogue’s Beauty Secrets since eighth grade.",
    "And I literally remember getting ready for, like, high school homecomings and stuff, like, watching Vogue Beauty Secrets videos.",
    "This is Charlotte Tilbury and it’s called Foxy Brown.",
    "This is, like, my year that I’m really focused on, like, my mental health, my emotional health, physical health.",
    "So I really love working out and like having a workout routine.",
    "It like releases all these different toxins.",
    "My next step is going to be the Fenty Beauty Lip Gloss.",
    "Like, I feel like that’s what people see the most when they see my face ’cause I’m always smiling.",
    "This is my KKW perfume and I’m obsessed with the scent.",
    "Feel like a little spritz, feel like a little twirl.",
    "Love you guys.",
    "[chill music]",
    "I’m gonna start with this, which is the African Botanics.",
    "I love this product.",
    "[chill music]",
    "Then, I put my oil on there so I just do.",
    "I’ve always had some kind of routine and I enjoy it more now that I’m older.",
    "I’m not religious about it",
    "that keeps me playing with my skin care routine and I change it all the time.",
    "[chill music]",
    "I do like to do eye masks under a full mask.",
    "[chill music]",
    "Everyone always asks me like, \“Skin care, skin care. Like what do you do? What do you do?\”",
    "Three things: Sleep, hydration, supplement",
    "And for me, skin, like fine lines, hair, nails, this is my dream product.",
    "I’m gonna do two scoops of this beauty.",
    "This supports skin elasticity, stronger nails, hair.",
    "[chill music]",
    "meditation is probably the most important self-care that I do",
    "I know it sounds silly, but when you have your mask on, it’s actually a good time to do it.",
    "You can do a nice 10 minute meditation.",
    "I did these cocktail concentrates with my friend Karen over at Juice Beauty.",
    "This is matcha. This has got matcha in it.",
    "So it kind of like wakes your skin up.",
    "[chill music]",
    "This might be my favorite cream that I’ve used in a long time.",
    "Basically, this feeds and supports your microbiome on your skin, which is what your largest organ.",
    "[chill music]",
    "One of the most important things to me is sunscreen.",
    "Today, I’m using Barbara Strum Sun Drops.",
    "[chill music]",
    "I’m going to use RMS Beauty Foundation.",
    "This is a little different than I think what most people do.",
    "So, I take a little bit like this.",
    "I kind of go like this and now I play.",
    "[chill music]",
    "You know, tricks that you learn from your makeup artist.",
    "I go a little bit warmer than my normal skin tone.",
    "And then, I go around with paler product.",
    "So I’m gonna do the Kosas.",
    "I use the beauty blender sometimes too but I wanna do this fast, so I’m gonna do my fingers.",
    "[chill music]",
    "I’m gonna go in with a contour now.",
    "This is Gucci Westman.",
    "I love all kinds of makeup looks.",
    "We’re gonna do a really subtle eye.",
    "It’s a stealer product. I love it.",
    "so I dab it on here ’cause I don’t want a heavy eye today.",
    "So now, because I have almond eyes, I bring everything under.",
    "I feel like everybody, every face is so different.",
    "And like you kind of have to find the part of your face you wanna accentuate.",
    "My whole life I wish it was my lips, but that’s not what God gave me.",
    "Now, I’m gonna put a little bit of one of my favorite highlighters on my lid.",
    "So this is the Luminizer Quad.",
    "The one that I obviously use the most for my skin tone is this here.",
    "So, I take that. Again, I’m using my little hand palette.",
    "[chill music]",
    "This is actually a product that I have no idea what it is but it was sent to me.",
    "And it’s called Petite ’n Pretty.",
    "And it’s called Fully Feathered Volumizing and that honestly is exactly what it feels like it does.",
    "I like clean product because my skin responds to it better.",
    "So brows are my least favorite thing to do ’cause I’m really not good at them.",
    "It’s kind of like that TikTok thing that has all this stuff.",
    "[chill music]",
    "This looks weird now, but it’s not gonna look weird soon.",
    "[chill music]",
    "That’s sort of like a person who doesn’t know how to do brows way to do brows.",
    "I’m gonna use Monika Blunder who by the way has the best product line.",
    "So, here’s the Liquid Flush.",
    "I kind of go a little bit heavier on my cheekbone",
    "[laughing]",
    "When certain people have started doing their own product lines, I can trust them.",
    "I’m gonna do a little bit of this. This is By Terry.",
    "This bottle’s taken me years to get through.",
    "[chill music]",
    "[lips smacking]",
    "I love you.",
    "[upbeat music]",
    "They’re zit stickers, but they’re the cute kind.",
    "It’s organic.",
    "This is my mask. It’s also Eminence.",
    "I totally succumbed to an Instagram ad",
    "While my skin’s pretty damp, I’m gonna put my serum on.",
    "Compliment yourself. It’s fun.",
    "I really do feel like I’m in a better mood.",
    "But it is natural and it’s oil free.",
    "spending time with yourself for yourself is definitely a big tool for me.",
    "But I don’t like having like makeup on my neck and ears and stuff.",
    "I’m gonna light some good old incense.",
    "Love this company, 100% PURE.",
    "The ingredients list looks like a smoothie.",
    "I absolutely despise the feeling of foundation on my lips.",
    "This was my first makeup ever that I got.",
    "My friend sent me all of this makeup to try from her brand",
    "Little bit of that. I don’t have to use that much.",
    "I try my best, you know. Nobody’s perfect.",
    "[gentle music]",
    "I use two different mascara.",
    "So this is again that brand, 100% PURE, that’s like literally made of food.",
    "It does not vibrate, but I’ll send an email to the company or whatever.",
    "Now I’m gonna do blush, which is another fun part.",
    "I just like found the true joy in makeup recently.",
    "I’m aware that I have a lot of blush on, but I want more.",
    "[gentle music]",
    "[gentle music]",
    "It’s called Oud Immortel. Or Immortal.",
    "I don’t know how to say things fancy, but it smells nice.",
    "[gentle music]",
    "[upbeat music]",
    "True Botanicals cleanser.",
    "I put some in my hand like this and I’m not afraid to put it everywhere.",
    "Penetrates the skin, supposedly, I just love the ritual of it.",
    "I love anything that’s pampering, and I’ll try almost anything. [laughs]",
    "Just because I think it’s just so much fun to just try new treatments and, and play.",
    "but I’m always trying new ones.",
    "My eyes get really red and they get really puffy.",
    "The first product that I put on my skin is the Chebula active serum.",
    "And Chebula is a very, very powerful antioxidant for the skin.",
    "When I’ve used retinol in the past, I’ve gotten really irritated and, and sort of dry and almost flaky.",
    "I feel like it’s waking up my face, waking up my skin.",
    "I love thick, delicious creams.",
    "My last step of skincare it’s super goop glow screen, and it’s SPF.",
    "I feel glowy. I feel refreshed. I feel ready.",
    "Instead of using a liquid foundation and a brush, it’s an airbrush machine.",
    "I like this, it’s the Urban Decay Naked palette.",
    "I love Color Stick, and love just putting like, just here.",
    "Eyelashes, so this is Thrive.",
    "There’s something about mascara that I am crazy about.",
    "I just like a gloss, this is Laura Mercier.",
    "This is the nutrient mist, also from True Botanicals.",
    "Bye. [blows kiss]",
    "Today, I’m gonna be using the Alo enzyme cleanser.",
    "Now steam is actually a major key in revitalizing dry skin.",
    "I’m obsessed with this clay mask. I’m having too much fun.",
    "[bright music]",
    "The lip mask I’m using is Laneige.",
    "Now I have all these dark marks, discoloration, sun spots.",
    "Sending you all love. All good energy.",
    "I like to start with Olive oil.",
    "I used this biodegradable like, single-use face towels.",
    "I get this from the Natural Face Bible.",
    "I really swear by, like, face training and doing, using a face roller.",
    "I started doing this and it just really helped with lymphatic drainage.",
    "I use this 100% Pure Coffee Bean Caffeine Eye Cream.",
    "I have like a whole nighttime beauty routine, that no one’s gonna stand on the way of.",
    "One more moisturizer that I apply, this is Weleda Skin Food.",
    "So my last step before I put on my makeup is I use Barbara Sturm’s sun drops.",
    "I listen to TikTok when they tell me what I should use product-wise.",
    "I use this DM Yummy, I guess it’s a powder.",
    "This is also by Milk, it is the Grip eye primer.",
    "In that case, I would use the Cle De Peau, little beauty concealer sticks.",
    "And I like to put it underneath my lips, ’cause it also enhances your lip line.",
    "So, recently a little birdie that told me to try the Got2b Ultra Glued.",
    "I then will let these dry by taking a hair dryer, and drawing my eyebrows. [giggles]",
    "So when I do my eyes, I use both Charlotte Tilbury palettes.",
    "I am very much so, still a little bit of a drugstore makeup girly",
    "I use Aqua Forte.",
    "So, I hope you enjoy your day.",
    "Skincare has always been really important part of my day.",
    "Going to use the Dermalogica exfoliator.",
    "I love this one because it’s really gentle.",
    "I’m going to use the Face Gym.",
    "I’m feeling a bit blocked up at the moment and it just really feels nice.",
    "I use eye cream because as you can see, my eye bags are bright purple.",
    "[laughs]",
    "This is the Youth To The People one.",
    "Probably one of my favorite parts of my skincare routine is my Laneige lip mask.",
    "This is my mom’s Sacred Mist from her new brand.",
    "My first step is skin tint.",
    "My Beauty Blender is already damp, I’m just blending this out all over my face.",
    "I always find cool inspiration on TikTok and Pinterest.",
    "I’m going to go back in with my Beauty Blender and just blend out the Nars",
    "Guys, I just found a bit of concealer that I didn’t blend out.",
    "I take a bit of this and a tiny bit of the medium brown.",
    "if I do the bottom lashes, it falls down and then it creates darkness.",
    "Give them a bit more attention and love.",
    "Lip liner is definitely a process.",
    "It’s my favorite thing ever and I can’t leave the house without this either.",
    "It’s like my \“no makeup, makeup\” look.",
    "[soft music]", // BEGIN SEPARATION
    "I am a very puffy, puffy girl in the face",
    "My skincare journey has been a very interesting one.",
    "This mask is really hydrating.",
    "I use this face roller tool.",
    "This pure hydration serum.",
    "This is the moisturizer I’m using these days.",
    "I like to use this alone.",
    "This is the sunscreen and kind of like skin tint that I’ve been using.",
    "This is my favorite lip product in the world.",
    "I rub it between my hands until it’s super warm and like oily and then I just put it all over.",
    "The sunscreen that I used earlier is tinted and just helps.",
    "I put this directly on my face, mostly on the spot where there’s like noticeable discoloration.",
    "Also, I don’t remember where I learned this trick.",
    "I love blush so very much.",
    "This is my favorite highlighter in the history of the world.",
    "Curl in the lashes",
    "These are the pencils that I use to get a color that makes me happy.",
    "It’s like a chocolate color.",
    "I would not leave it just like it’s too pink for me.",
    "This is the lip balm situation and it’s really good and it’s on the mauvie side.",
    "Brow gel is my most favorite makeup product.",
    "This I love ’cause it makes it look like more intentionally messy.",
    "I hope that you’re happy, healthy, safe, hydrated, loving and kind to your family.",
    "Bye, muah!",
    "Because I wear individual lashes, I have to go around my eyes very gently.",
    "[bright music]",
    "And I have pretty thick eyebrow so I don’t need to do a lot.",
    "I use a concealer just to shape it.",
    "I started experimenting with makeup about 16, 17.",
    "Nobody else knows your face better than you.",
    "No foundation, guys.",
    "You also have to be mindful of what you eat, ’cause what you put inside, kind of like, reflects on the outside.",
    "You always have to finish up with perfumes, ’cause I’m obsessed with how I smell.",
    "[light music]",
    "what is really special about our line in particular is that we have the Tri-C Pro-Peptide.",
    "Helps with the brightening of your skin.",
    "It helps with also the pigmentation, the evenness of your skin.",
    "Another thing that I’m obsessed with in the process of getting beautified is the eyebrows.",
    "I feel like you don’t have a face without eyebrows being right.",
    "I just go and I get those little bitty details there.",
    "This is liquid gold for the face.",
    "Next up that I’m gonna do is my face roller.",
    "You wanna rub up here, and what it does is it helps lift the muscle.",
    "spread it all over the face as a base and it helps, again, to even out skin.",
    "Little classic eyelash curl.",
    "Setting spray, ’cause it’s really fun.",
    "Now it’s time for me to go and do better things, baby.",
    "[mellow music]",
    "This just reminds me to take a minute for myself in the morning.",
    "Have my coffee and it’s just a lovely morning self-care ritual that I do.",
    "And you know, once in a while I get a facial just for maintenance.",
    "I do some hydrating eye cream.",
    "My last step for my skincare routine is using this face roller.",
    "So my skincare education came from YouTube",
    "I definitely think that it helps with puffiness and inflammation.",
    "Now, we’re gonna head into my winged eyeliner look.",
    "I do two rounds of blush.",
    "Second round of blush after highlighter is a cream blush.",
    "Just taking like the lightest most chill brown, and just popping a little bit in the crease.",
    "The last step to tie this all together is just adding a little freckle.",
    "I’m very excited to tell you about my new brand.",
    "This is a rose quartz candle.",
    "It just brings peace and calm to my start of my day.",
    "I’ve been meditating, doing yoga, just being much healthier.",
    "I was trying new things, all of this stuff that can make you feel more grounded and balanced.",
    "I’m just gonna work into my skin and my neck.",
    "It’s very healing",
    "It has a blackberry CBD, which is good for everything",
    "I kind of use a shadow",
    "[kissing]",
    "I wear makeup basically every day when I’m filming on set.",
    "Little eye mask.",
    "I get like super puffy eyes when I first wake up.",
    "Because I do not wanna look like a raisin when I’m old.",
    "I’ll just go on the parts of my face that I kind of want to be accentuated.",
    "I love Korean makeup and skincare.",
    "I do this thing where I basically just go and kind of blend it in",
    "I think it’s my favorite part of my face.",
    "I feel like I usually lean towards the more richer lip colors",
    "[blows kiss]",
    "Well, I would start off with a cleanser",
    "Gonna wash it off [claps].",
    "It kind of primes, it makes you glowy.",
    "Makeup for me, it has always kind of been a ritual",
    "I think we just all have our own little beauty rituals",
    "It’s glittery and it’s pink",
    "I’ve been obsessed with kind of the smell of this",
    "I’ve made a lot of mistakes with makeup, and that’s when I learned.",
    "Most of my products now, are things that I’ve used for years.",
    "I think it’s been like almost 10 years, that I’m using this concealer",
    "I definitely get inspiration for my looks, from life.",
    "I used to kind of go a little too crazy on contouring.",
    "This is a queen product.",
    "This is a cult favorite.",
    "The iconic little nose tap [laughs].",
    "[gentle upbeat music]",
    "I really do like doing my skincare.",
    "It’s always so hard to like color match as a woman of color.",
    "It is hard to like get makeup sometimes.",
    "I learned that from TikTok.",
    "a little bit of eye bags action.",
    "there’s a spectrum of how much you can do your makeup or how little you can do your makeup.",
    "I personally like the orangey-brown tones.",
    "Feel like if you do the full way, that’s a little much.",
    "Lash glue, pro tip, never put lash glue on with the lashes facing you.",
    "This is very influenced by like TikTok",
    "I like to just make sure we’re still staying dewy.",
    "I’m feeling pretty confident right now.",
    "Yeah, like there’s barely a difference.",
    "[smooth music]",
    "About one time a week, maybe, I try to do a mask.",
    "Again, major self-care luxury solo time moment.",
    "I don’t see it, I don’t feel it",
    "in this color that is called Golden Light.",
    "[chill music]",
    "I’m definitely the girl on the plane with the acne stickers.",
    "I’m comfort over everything.",
    "This really helps brighten any dark hyperpigmentation",
    "[laughing]",
    "So what I’m doing is starting from the outer and working my way in",
    "so I can just create more snatched look",
    "I typically go a few shades lighter",
    "I feel cute.",
    "I really love this gloss on the lid",
    "[mellow electronic music]",
    "this bad boy that I got off Amazon",
    "I have had a skincare routine since I was like 12-ish.",
    "Right now, my skin is feeling really good",
    "[giggles]",
    "So for me, I find a lot of like peace in it",
    "I don’t feel like I need to do that at this exact moment.",
    "Cold water, don’t use warm water",
    "put like about that much.",
    "I love this shit.",
    "I wanna look like somebody just dipped me in honey.",
    "I feel so much better when I feel good about my skin.",
    "and it’ll just kind of give some volume.",
    "I also use cuticle oil",
    "This is the lotion that I use.",
    "a little spritz of fragrance",
    "It makes me feel really good",
    "I really love this product so much",
    "Now, as you can see, there’s a tint to it",
    "Only maybe five years ago did I get serious about skincare",
    "I have been extremely regimented about my eating.",
    "I’m gonna curl the lashes.",
    "I love this brush so much.",
    "I love this powder so much.",
    "[inaudible]",
    "I have always really liked makeup.",
    "So I’m just gonna go under the eye.",
    "I also like to go in there.",
    "I’m gonna finish this off with my cheeky lip",
    "[pops lips]",
    "I’ve always kind of had a skin care routine.",
    "Only wash my hair a few times a week.",
    "[soft jazz music]",
    "Texturizing cream.",
    "This is a Japanese product, actually.",
    "The next step is curl cream.",
    "♪ You’re just a man ♪",
    "[lo-fi music]",
    "helps to give you that glow.",
    "leaving it plump and dewy and glowy.",
    "I feel like makeup just sits so beautifully on top of these products.",
    "I’m gonna tap it under my eyes.",
    "I just love the routine of skincare, I always have.",
    "I love the ritual, the commitment to skincare",
    "Self care, it’s like at home, in a bath",
    "I love glowy foundation.",
    "I’m applying it with my hands.",
    "I just love that it’s creamy and hydrating",
    "you guessed it, I saw it on TikTok",
    "Placing it there definitely makes a big difference.",
    "a little bit, it’s not overpowering.",
    "A little goes a long way.",
    "I’ve definitely gone on a brow journey.",
    "I don’t know why I’m making my life complicated.",
    "I’ve realized that for me, more subtle is better",
    "just right here in the Cupid’s bow",
    "I had so much fun [blows kiss]",
    "I typically find my products through like SkinTok, on TikTok.",
    "SPF is the most important step.",
    "My undereyes don’t actually really bother me",
    "Kind of like a one product for everything.",
    "I’d put it like all on my waterline",
    "[blows kiss]",
    "I go back and forth with cleansers",
    "a really gentle oatmeal cleanser.",
    "I love this brand",
    "This one’s really light and easy",
    "I always had really dark circles",
    "It just kind of helps everything be a little smoother.",
    "Oil but you just put a little tiny bit",
    "I do like a full brow.",
    "Just like to use really gentle strokes.",
    "this next part gets messy",
    "you just want to rub it in",
    "i also will put it on my eyebrows",
    "it’s an oil that hydrates your lips",
    "i love purple on brown skin",
    "i use these little tiny q-tips",
    "and then i just curl my eyelashes",
    "just with my finger just a little bit",
    "i make my own perfume",
    "[soft music]",
    "First, I will turn my face steamer on.",
    "Just makes my skin texture look much brighter.",
    "I will exfoliate my body.",
    "My skin feels so soft.",
    "It makes my face sort of more awake and tighter",
    "Now we have a gua sha.",
    "And I will just pat it.",
    "As you can see you pump it.",
    "I just put a little bit on",
    "I’m just gonna blot it a little bit.",
    "And I’m gonna use this microfiber towel.",
    "I’m really obsessed with neck skin.",
    "I love big bold colors on the mouth.",
    "I’m aging a lot in both directions",
    "[calm music]",
    "[laughs]",
    "I don’t know if I put too much on",
    "Do you know what I use this for sometimes?",
    "I have this Tom Ford one.",
    "I use this once or twice a week.",
    "so I use these ice rollers.",
    "This is great de-stress.",
    "I hate when it looks shiny and glossy.",
    "I started getting lash extensions",
    "I just can’t be bothered basically.",
    "I’m gonna move on to my lips.",
    "I feel like this kinda lifts.",
    "I only use like a couple of drops.",
    "always go up, don’t pull down.",
    "I like do this tapping thing",
    "I’m here with Vogue \n[hands clap together]",
    "instant [fingers snap] little serotonin.",
    "This is not all my real hair.",
    "[lips kiss]",
    "I’m usually really rough on my skin",
    "I’m an eyeliner girl.",
    "I don’t like it to be super bright under my eye.",
    "[mellow music continues]",
    "You know, things happen",
    "Two or three drops.",
    "Now [sighs] we’re gonna do our wing.",
    "take a deep breath [laughs]",
    "[soft upbeat music continues]",
    "I use these when I’m having breakouts.",
    "This is the scariest part.",
    "Just get in and go for it.",
    "I also have this cat makeup bag.",
    "Next I’ll use this beauty blur.",
    "Like this never moves, it’s so good.",
    "leave it on for about 10 minutes.",
    "and yeah, I love doing self-care.",
    "I mean, TikTok helped me discover it",
    "Moisturizer. [giggles]",
    "But you just get on with it.",
    "I love all their products.",
    "So again, going right there",
    "[relaxed music]",
    "I find it really gives you that dewy, glowing look.",
    "So, I put baking soda on my face",
    "I’m still not good at makeup",
    "When I’m stressed out, [laughs] I just dab a little bit of this.",
    "I like to go in with the eyes first.",
    "I kinda just keep it on my T-zone.",
    "So I use everyday, turmeric and ginger elixir",
    "So I mix it with my favorite water, Fiji",
    "cleanse cleanse cleanse",
    "how much time am i worth to myself",
    "It’s really relaxing.",
    "And now it just blends beautifully.",
    "I, ah, just, everything feels so cool.",
    "that adds as another little moisturizer.",
    "Use the dry corner.",
    "I think it has ultra-something red light.",
    "Mostly, I like to just depuff with it.",
    "move those toxins out of your body",
    "I really believe in doing little things that make you feel good.",
    "I just spray my face with this face mist",
    "I have baby cheeks. See?",
    "If I’m stressed, I break out.",
    "[playful music]",
    "kinda like a pudding for your face.",
    "It’s just that this has everything.",
    "[calm hip hop music]",
    "just like super, I don’t know, romantic",
    "What am I, like fancy? [giggles]",
    "I think it’s always like a nice sun kissed feeling.",
    "but it looks professional, right?",
    "it’s just coconut oil and CBD.",
    "does it make you feel fun to have a lipstick on?",
    "My secret weapon is a caffeine eye cream.",
    "Hopefully encourage a bit of drainage of the puffiness.",
    "I wanted to try every product.",
    "I wanted to have an opinion on every product.",
    "I’m doing a mascara base.",
    "You’re gonna do one more coat",
    "you’re just gonna do it with your finger",
    "I started enjoying taking care of myself",
    "believe it or not ice is my best friend",
    "beauty really starts from within",
    "So I have always worn it and I obsess over it actually.",
    "Roll it up, and then just go, get a little.",
    "I just do, like, maybe one pump.",
    "Oh, it feels so good",
    "i am really strict with myself on my skin",
    "i could do this all day",
    "But for me, this is all I got.",
    "Muah [lips smack]",
    "I love crystals.",
    "I’m very into crystals.",
    "I do that also with my face rollers that are crystal.",
    "sometimes it’s good to use your fingers",
    "make it look shiny and cute",
    "I’m really extra, so I like to get a lot on there.",
    "It lasts all day.",
    "Lips have been scrubbed.",
    "I just like to keep it really natural and glowy.",
    "It’s just super subtle.",
    "So, let’s get into it baby.",
    "Or actually, this is a serum, excuse me.",
    "this toner deeply cleanly pores",
    "you’re definitely investing in yourself",
    "I’m a massive exfoliating junkie.",
    "And it just gives you a nice little [kissing] pink.",
    "I just put a few drops of the one shade",
    "You can get it like that.",
    "Like a little dab.",
    "you can never have too much blush",
    "It just completes my whole vibe",
    "But, you see the vision.",
    "I don’t know if they’re that many secrets",
    "That feels so good.",
    "So next up, a little bit of mascara.",
    "so this just really has everything",
    "it’s honestly made a difference for me",
    "So I just do literally just a whole pump.",
    "Like that.",
    "This is my lip gloss from my collection.",
    "That’s my aura cleansing mist.",
    "I’m a little darker right now",
    "you’re gonna need a good exfoliator",
    "i turn gray and gray is not cute",
    "more highlighter more highlighter",
    "a little bit of aloe got in my mouth",
    "leave it for a little bit, maybe sing a song.",
    "just a nice little light color",
    "We have to go feature our lips now.",
    "I go in real close to the mirror",
    "Dab that face clean.",
    "i’m gonna do foundation",
    "I just think, you know, dab, get it on.",
    "I get lazy with my routine.",
    "I just think that you’re special.",
    "You’re supposed to be who you are.",
    "Just a little bit, just to create a little shadow.",
    "femininity has power.",
    "Just being a woman [giggles] is quite politicized",
    "I hope you feel beautiful",
    "Beauty Counter Blush Stick in Caramel.",
    "I’m gonna take my Item Concealer.",
    "My KKW Beauty Bronze and Shine Palette.",
    "So I used a brand called Oliveda",
    "It is our GOOPGLOW Microderm Instant Glow Exfoliator.",
    "laura mercier this one’s really good",
    "So first step, this YSL beauty touche eclat.",
    "and I’m gonna use this Gucci mascara.",
    "i’m gonna use the dior lip maximizer",
    " a special one called Stiletto Cream.",
    "This is the Glossier Sky Wash.",
    "I found this Kosas bronzer at Sephora.",
    "I use this Glacier Water Hyaluronic Acid Serum.",
    "I’m using this Glossier one.",
    "Laura Mercier, another classic, all time favorite.",
    "I use the Tatcha Rice Wash",
    "I use this Dior quad.",
    "The Osea Sea vitamin boost.",
    "I like Lush’s stuff",
    "This is just a MAC black gel liner.",
    "It’s called Good Genes",
    "this is Gucci Envy Me.",
    "This is the bronzer, Bobbi Brown.",
    "Biologique Recherche.",
    "This is the Anastasia Clear Brow Gel.",
    "This is the Chanel blush.",
    "I really like kind of more matte products.",
    "This is a Benefit bronzer.",
    "Charlotte Tilbury pencil.",
    "This is a JILLIAN DEMPSEY Lid Tint",
    "This is a Kosas concealer",
    "This is a Sisley Primer of sorts.",
    "This is, ISDIN Actinica.",
    "Next I’m gonna use the serum",
    "Elizabeth Arden, Eight Hour Cream.",
    "What I’m gonna start with is Clinical Firming Copper Mist.",
    "I use Living proof, Perfect Hair Day In-Shower Styler.",
    "I’ll put on this COOLA Organic lip oil.",
    "I use this Chantecaille Anti Fatigue Correction Pin.",
    "I’m gonna use Kate Somerville’s KateCeuticals Total Repair Cream.",
    "Kate Somerville KateCeuticals Lifting Eye Cream.",
    "and the one that I love is this MARA Universal Face Oil.",
    "Here is the NuFACE, my favorite little thing.",
    "Next, what I do is I use my NuFACE",
    "I’ll use Kate Somerville’s ExfoliKate, the body version.",
    "I’ll use this Kate Somerville ExfoliKate.",
    "I have this Organic Pharmacy Carrot Butter Cleanser.",
    "this urban decay blue eyeliner",
    "this laura mercier number six",
    "i use nars",
    "this dior show eyebrow pencil",
    "i really love this armani luminous silk",
    "i use this laura mercier primer",
    "i use christine chin cleanser",
    "This one’s Pure energy.",
    "We’re gonna use Ilia and just do some mascara.",
    "So I just have a Charlotte Tilbury lipstick",
    "I have this product, which is from Urban Decay.",
    "the Glossier Pro Tip.",
    "I will start with eyeliner, Charlotte Tilbury.",
    "So I’m gonna use a little bit of this Laura Mercier powder.",
    "I just use this little Glossier Cloud Paint.",
    "I really, really love the Fenty Beauty Soft Matte Longwear Foundation.",
    "I’ve got this really great one from Ilia.",
    "This is the Kosas Cloud Set powder.",
    "the Tom Ford Shade and Illuminate palette",
    "Dior Backstage Rosy Glow powder blush.",
    "I’ve talked about this Makeup Forever palette before.",
    "MAC Extended Play Gigablack Lash.",
    "This is the Anastasia clear eyebrow gel.",
    "This is the color Perfect Storm.",
    "This is the Kylie Cosmetics Stormi palette.",
    "This is Ariana Grande’s brand",
    "The base that I’m using for the eye is REM Beauty.",
    "This is the Kosas concealer.",
    "I love the Chanel Vital Lumiere.",
    "the Dieux Forever Eye Mask.",
    "Barrier restore cream",
    "Next I’m gonna go in with the Rhode peptide glazing fluid.",
    "I’m gonna start with this Environ moisturizing toner.",
    "This is YSL 24.",
    "It is called Nipple Balm.",
    "This is one that I use from Authentic Beauty Concept.",
    "CeraVe moisturizing cream.",
    "CeraVe hydrating facial cleanser.",
    "I got it from Target for like $10.",
    "I’m gonna use Burt’s Bees.",
    "And so there’s a certain nostalgia that comes with Benefit makeup for me.",
    "So I’m gonna use this Benefit product, High Beam",
    "I’m going for Marc Jacobs.",
    "I use the doctor Hauschka Eye Definer number two.",
    "So I’m gonna use the Charlotte Tilbury Desert Haze palette.",
    "It’s called BrowKiki.",
    "It’s the Benefit Dandelion.",
    "It’s Light Plus Mineralize Skinfinish",
    "I’m gonna use this mac lipstick",
    "I’m gonna go for this Charlotte Tilbury",
    "It’s so good, the coverage is amazing",
    "I’m just gonna do a little Aquaphor.",
    "So I’m gonna do my moisturizer, which is Lamer.",
    "I take this Rejuvi Flavonoid Complex,",
    "Number one. Rejuvi.",
    "Here’s my fragrance, Eilish",
    "Laura Mercier, it is so nice.",
    "I take the love of my life, which is Aquaphor Healing Ointment",
    "I use a lot of Olaplex products for my hair.",
    "But what I like to do at night is use this Olaplex Number 6.",
    "from Biba, this is her cream barrier.",
    "go back in with the Fenty palette",
    "My YSL Mascara.",
    "I actually use two different shades by Dior.",
    "I’m gonna go in with my YSL Concealer.",
    "I’m gonna go in with my Fenty Powder.",
    "I’ll use my Dior, right here.",
    "Fenty Translucent Powder.",
    "I like to use my Anastasia Brown Pencil because it gives natural strokes.",
    "I’m going to apply my Pro Heal Serum.",
    "This is my favorite cleanser",
    "I use this Dior beauty palette.",
    "I use the Chanel mascara.",
    "I have used the Nars Orgasm color forever.",
    "Chanel eyeliner.",
    "I use this Chanel Essentiel stick.",
    "I use the Benefit Gimmie Brow.",
    "So I use Supergoop Unseen Suncreen.",
    "I love this Tata Harper resurfacing mask.",
    "I use Whipped Dream by Isla.",
    "I used Pharrel’s Humanrace skincare.",
    "I use Kiel’s",
    "It’s tinted from Fenty Beauty.",
    "We’re gonna go with Milk.",
    "Next blush, Tata Harper.",
    "Charlotte Tilbury blush.",
    "Urban Decay, just the darkest shade.",
    "Really quickly, we’re gonna go in with this KVD eyeshadow primer.",
    "Brow gel time, this is from Kosas.",
    "NARS concealer, this is the go-to brown girl concealer I think ’cause it just gives you great coverage.",
    "This one is from Armani.",
    "This one is from PÜR.",
    "So we got Milk over here with their Hydro Primer.",
    "I just use a face wipe, also from Epicutis.",
    "You got this serum from Epicutis, a little goes a long way.",
    "As a last step, Fix+.",
    "I’m using Charlotte Tilbury’s little duo.",
    "It’s Push Up Lashes by Charlotte Tilbury.",
    "Charlotte Tilbury.",
    "Space Cowboy, Urban Decay.",
    "I remember like with the first makeup item, that I like saved my pocket money on, and was obsessed with, was this Dior cream eyeshadow ring.",
    "I’m gonna use Fix+ by MAC.",
    "It’s the Dior Skin Glow.",
    "This is Glow Recipe.",
    "It’s by MDNA Skin",
    "Kiehl’s Ultra Facial Cream",
    "This avocado eye cream by Kiehl’s, was one of the first eye creams I think I bought.",
    "This is called the Glow Stick.",
    "This is from Supergoop!",
    "I’m just gonna go in with this Charlotte Tilbury lip liner.",
    "I’m gonna go in with this Tarte Chrome eyeshadow pot.",
    "Then I’m gonna go in and curl, and then I’ll use this Hourglass mascara.",
    "I’m gonna go in with this Charlotte Tilbury liquid eye pencil.",
    "I love brands like Innisfree, I think they’re great.",
    "It’s just the göt2b glued gel.",
    "This is the Hourglass warm brunette pencil.",
    "I’m using the Fenty setting powder.",
    "I use the Charlotte Tilbury lip and cheek.",
    "and then this Drunk Elephant Bronzer",
    "Underneath this place is Dior Foundation.",
    "So I start with the Charlotte Tilbury Wonder Glow.",
    "La Mer under eye Balm, and I’ll just take a little bit on my finger.",
    "First step, I use my Curology cleanser.",
    "I will have a spray of Sacred Mist.",
    "It is Sam McKnight’s hair product, Cool Girl, which he said he made for me, ’cause my hair was always a little bit shabby looking.",
    "So now I’d use the Golden Nectar.",
    "This is Leneige.",
    "Anyway, I’ve been doing the Cosmoss moisturizer, and it’s made from oakmoss as well with CBD.",
    "So this one’s from Santa Maria Novella.",
    "It’s called Cosmoss",
    "This one’s from & Other Stories.",
    "This is Oribe’s Gold Lust Hair Oil.",
    "This is Freck.",
    "Burt’s Bees chapstick.",
    "I line my lips with this MAKE UP FOR EVER Aqua Lip Pencil.",
    "I’m using this Kosas Breezy Cloud Set Powder.",
    "It’s by Stila Stay All Day Waterproof Liquid Eye Liner.",
    "HUDA BEAUTY Palette, I put a little Sanrio sticker on there.",
    "Urban Decay Eyeshadow Primer Potion.",
    "So I use this Hourglass pencil.",
    "I use Sunnies Face.",
    "This is the Charlotte Tilbury Beauty Light Wand.",
    "I use this bronzer stick from Westman Atelier.",
    "This is Summer Fridays CC Me Serum.",
    "I’m gonna go in with some eye patches from Peter Thomas Roth.",
    "The ingredients are super simple and I put it on this vibrating cleansing pad from FOREO.",
    "This one’s from Farmacy.",
    "Got the R&C fragrance.",
    "Now what I’m doing is I’m highlighting my cheeks, so I have the iconic London blush and highlight palette.",
    "I’ma do Makeup by Mario Bronzer.",
    "All right, so now it’s time to seal the deal with the Danessa Myricks powder.",
    "I have my Nyx palette right here.",
    "I use this Yummy Skin Danessa Myricks face toner.",
    "I have to use my girl Lala, her Inala Hair Power Potion for the edges.",
    "So I use the Murad SPF 45 on the skin.",
    "OAM Radiance Moisturizer.",
    "Face mask by 111SKIN.",
    "I am sharing with you guys for the first time my skincare line",
    "So what I use is the Got2B Glue Gel",
    "And I use this edge control called Truth by Tasala.",
    "I’m going to use a Mac lip liner, which is called Nightmoth.",
    "I have my very own lipstick from Mac.",
    "This is Makeup Forever.",
    "I add a little blush and I use NARS.",
    "I also love this highlighter from Fenty.",
    "This Dark Deep Mineralizer from Mac.",
    "Laura Mercier and I use this to bake",
    "Purple and Prosper Calm Complexion",
    "I use Aqua Forte.",
    "Dermalogica exfoliator",
    "I’m going to use the Face Gym.",
    "This is the Youth To The People one.",
    "Probably one of my favorite parts of my skincare routine is my Laneige lip mask.",
    "My skincare routine is not complete without some Cosmoss.",
    "Glossier Stretch Concealer, which again is scratched and very much used.",
    "Nars Creamy Concealer.",
    "I use the Charlotte Tilbury Contour Wand.",
    "For the eyes, I use Charlotte Tilbury.",
    "Charlotte Tilbury highlighter.",
    "A Lancome mascara.",
    "The Beverly Hills Anastasia Clear Brow Gel.",
    "Pillow Talk by Charlotte Tilbury, a classic.",
    "And then we’re going to use the Fenty Beauty lip gloss.",
    "clearasil cleanser.",
    "this thing called Age Intervention Peptide Extreme.",
    "The Tom Ford Illuminating Primer.",
    "It’s the Lineage sleeping mask.",
    "This is the Westman Atelier Foundation stick.",
    "This is the Nars Creamy concealer.",
    "This is also Westman Atelier and it’s the bronzer contour.",
    "This Tower 28 is an all time favorite",
    "Glossier Cloud Paint, another classic.",
    "a tiny bit of the Cloud Paint.",
    "It’s Chanel, it’s really great.",
    "This is a Cover Girl eye pencil.",
    "This is Surratt.",
    "This is the Pillow Talk in medium.",
    "This Glossier lip in the shade Trench",
    "I used the Anastasia Brow Freeze.",
    "This is called Freck.",
    "So my next step is a serum from Obagi.",
    "finish it off with a Tata Harper Spring Mist.",
    "I use this Huda Beauty eyebrow pencil.",
    "I use a daily cleanser from Vanity Planet.",
    "I like that, I like that.",
    "[blows kiss]",
    "I have it in like three colors",
    "This is my Dior palette",
    "my favorite, favorite, favorite palette.",
    "I like to do a little ice cube facial.",
    "it’s honestly been so therapeutic",
    "Oh my gosh, it smells so good",
    "I found this great product that I love",
    "[light music]",
    "I just use a little bit of this on a little bit of this",
    "[exhales]",
    "I wanna feel toned, tan, fit and ready.",
    "So I just dab dab and I dab",
    "So I use Fenty Beauty Mocha.",
    "I’ll just tap it onto my skin.",
    "[upbeat instrumental music continues]",
    "[blowing air softly]",
    "[shaking bottle]",
    "[lips kissing hands]",
    "[calm piano music]",
    "I would love you forever.",
    "[mellow music]",
    "[laughs]",
    "I pretty much only use CeraVe",
    "and you just kind of roll it on your face everywhere.",
    "and stuff like [compact clicks] that",
    "This one’s by Chanel",
    "I’m gonna zhuzh my hair a little bit.",
    "I’m obsessed with skincare.",
    "[brush taps]",
    "I try to just get the, oops [laughs]",
    "So you just like, [brush taps] excess.",
    "And now she’s all glowy.",
    "This is the Thrive Liquid Lash Extensions.",
    "My skin looks almost perfect.",
    "Make my lips a little sparkly.",
    "something about that feels good",
    "Exhale, [exhales], do that about 10 times",
    "First this is a big secret of mine.",
    "This is Olay hair removal.",
    "It makes me feel so beautiful.",
    "This is my beauty elixir misty thing.",
    "sorry I’m just a little goofy sometimes.",
    "and put it on my face [giggling]",
    "Too Faced, the Chocolate Bar.",
    "So I’m gonna take my MAC Prep and Prime spray",
    "[laughs]",
    "this Barbara Sturm hyaluronic serum.",
    "This is my second favorite serum",
    "the Tarte Double Duty Beauty Shape Tape",
    "I don’t like to hide my freckles.",
    "[Speaking foreign language]",
    "[speaking Korean]",
    "Drain out the bad vibes!",
    "Oh it smells peachy too.",
    "[gasping]",
    "My face but better, with the glowy healthy skin.",
    "slather it on, and... relax.",
    "The next step is my La Mer Concentrate.",
    "Pulse pulse pulse.",
    "I love love love a pink blush.",
    "So I clip my hair out of my face",
    "I just do it until I feel like I’m snatched enough.",
    "[lip balm clicking] So ASMR",
    "I want my lashes to be seen from Mars.",
    "I’m using the Duo lash glue, by the way.",
    "La Mer moisturizing soft cream, from here up.",
    "Mac Extended Play.",
    "Clearly love Kylie gloss.",
    "It’s a shea butter antioxidant mask",
    "Also, [laughs] I’m nervous,",
    "I have gotten into this Glossier concealer.",
    "And then you can leave for 10 minutes.",
    "[blowing kiss]",
    "[sighing]",
    "This is a Dior Backstage Lip Palette",
    "Highlight, contour, so brilliant.",
    "[soft electronic music]",
    "[spritzing]",
    "And then I like. [tapping]",
    "But I like the blue mascara.",
    "Oh, I’m still so glowy, yes!",
    "Glossier Boy Brow, so good.",
    "I’m like, crying thinking about it.",
    "I’m a huge fan of this particular product.",
    "You can tell I really use it.",
    "I use Charlotte Tilbury.",
    "Tap off the excess.",
    "[dramatic music]",
    "Burt’s Bees Cleansing Oil.",
    "I remember being on Pinterest [tapping]",
    "But then it goes on like this.",
    "but the Lavender one just smells nice.",
    "Oh, blush! [giggles]",
    "obviously I love boy brow",
    "I am a big believer in lymphatic drainage",
    "[optimistic music]",
    "You see how my face is literally changing right before your eyes?",
    "And I’m gonna dip this into the bronzer",
    "I want it to look like I’m wearing no mascara.",
    "Getting rid of all those wrinkles.",
    "So you don’t wanna overdo it with oil",
    "This fancy jar is La Grande Creme.",
    "This is so intimate.",
    "It just accents it a little bit.",
    "This is from Laura Mercier and it’s a brightening powder.",
    "My toner! [laughs]",
    "♪ Serums ♪",
    "So I’ll do a layer, then I’ll just wait.",
    "my rose quartz gua sha.",
    "I like it to look super creamy",
    "[imitates crying]",
    "We’ll do a little pink, a little brown",
    "It’s by this brand, REN.",
    "because this is good for my dark spots",
    "mix it with that orange",
    "and it smells divine",
    "it’s called biscuit soft matte complete concealer",
    "I have horrible dark circles",
    "I’m just gonna hit the lids very lightly",
    "griffin ivy rose body oil",
    "this is very bold",
    "this is a major product",
    "it’s all organic and it’s made out of vegetables",
    "the secret to beautiful skin is exfoliation",
    "I always thought about my face as a canvas",
    "contour um this is a mac palette",
    "I really just pile it on",
    "and then you line the face",
    "and there’s no method behind this",
    "it’s my little applicator for my eye",
    "it’s just kind of the dream texture",
    "I am going to attempt to apply on both my cheeks and my eyelid",
    "for the eyes I just put this glitter thing",
    "I always bring with me this rose water",
    "I’m going to use this Revlon Colorstay",
    "it helps makeup look more natural",
    "my new favorite mascara is from l’oreal paris",
    "honey is also antibacterial and full of antioxidants",
    "setting spray kind of helps create a nice canvas for the makeup",
    "I’ve learned some tips little by little",
    "I love this NARS stick",
    "sometimes I take a tissue I go like this",
    "think using a base is very very important",
    "I love the Fendi primer",
    "I love a good textured skin",
    "I literally just use Burt’s Bees again",
    "you have to give your lips a treat",
    "I like my brows like messy",
    "I don’t fully put lipstick on",
    "and i’m going to use the kylie palette",
    "it’s a little more matte and not too like shiny and glowy",
    "you can smile so you can see your cheeks",
    "then I sort of go in on my nose",
    "okay so now let’s go to the contour",
    "it just kind of makes your lips a little bit pinker",
    "add a little bit of black",
    "I start with a face oil",
    "then your skin is very shiny and supple which I love",
    "the brow just really sets the tone for the whole face",
    "it really helps my face like it hydrates",
    "just an everyday glowy sunkissed look",
    "I think you’re also supposed to like tap",
    "like i said i’m obsessed with makeup",
    "my lash star beauty eyelash curler",
    "wait like 10 minutes before you wash it",
    "i’m using nova lipstick today",
    "i can’t do my makeup without baking",
    "nice little glowy everyday look",
    "it’s good for your lashes",
    "I like having gloss rather than just matte",
    "do it here in the crease of my eye wrinkles take it away",
    "so i have a little redness there",
    "you get greasy on the fly honey",
    "now for the glowing part",
    "I use this lip scrub from lush",
    "it’s really pretty and looks incredible in photos",
    "and i spritz it on my face",
    "this one is my favorite brand",
    "I’m using a Beauty Blender",
    "the most important part of eyeshadow is blending",
    "I’m using Smashbox full exposure",
    "I don’t really use brushes I use my fingers",
    "I always like to start at the top and move down",
    "and just smudge in so it looks like a cherry stain",
    "don’t forget the neck",
    "then I’m on to a light foundation",
    "sugar honey by fresh",
    "add a little bit of this color from NARS",
    "I’m using a NARS creamy concealer in caramel",
    "I always like the glow",
    "intensify your cheekbones",
    "double wear nude Estee Lauder",
    "I hate when I have like cakey makeup on",
    "I’m obsessed with blush",
    "let’s give it some life let’s give it some shine",
    "can I even show this?",
    "this is my ultimate secret",
    "it’s the Gucci eyeshadow pallete",
    "I’m going to stick my head in the sink",
    "this rose hibiscus coconut water hydrating face mist",
    "my eye gets so dry around here",
    "i start always with a clean face",
    "I think it’s the best eyeliner in the world",
    "one coat of this one",
    "so it literally like exfoliates",
    "a little dab of extra coverage",
    "eyelash curlers my nemesis",
    "I’m not into a perfect lip line",
    "I usually do about three dollops on my fingertips like this",
    "and wait for just a minute until it starts to tingle",
    "I always like matching my cheeks to my lips",
    "it’s all about getting your highlight together",
    "I have some spots but don’t we all baby",
    "my skincare is custom from clinique",
    "see just like wing it you know",
    "imperfections are still beautiful right",
    "just gonna spice up my eye",
    "it hydrates it moisturizes and it tightens as well",
    "this is like a little tip for you guys",
    "doesn’t need to be well done obviously",
    "so I start with some foundation",
    "Bumble and Bumble surf spray",
    "this is for sexy beachy windswept styles",
    "I love highlighter",
    "start with a base",
    "I like Mac face and body",
    "that’s the fun of makeup you can do whatever you want"
];


let documentationCaptions = [
    "I feel like this kinda lifts.",
    "I’m gonna do blush next.",
    "This is the Fenty Beauty Pro lip scrubber",
    "[gentle upbeat music continues]",
    "My eyebrows have their own toothbrush.",
    "I suffer from dark circles.",
    "A Lancome mascara.",
    "You can do some deep breathing.",
    "This cute Chanel bronzer.",
    "And I just go along the top of the eye.",
    "I use about that much.",
    "Here’s my little exfoliating wash cloth",
    "And you know, this is also very therapeutic.",
    "This is Pillow Talk Charlotte Tilbury",
    "I’m all about essential oils.",
    "Always pat your face dry, it retains moisture.",
    "This is another Hourglass product.",
    "And I start going up and down the nose.",
    "My skincare routine has gotten more and more complicated."
];


