
let comments = [
    "the makeup didn’t do anything, that’s how pretty she is naturally, wow",
    "step 1: be incredibly gorgeous",
    "Absolutely love her. One of a kind that one. She is darling. So effortless, cheeky, quirky with a twist of glam, I don’t know how she does it. She is beautiful inside & out.✨",
    "She doesn’t need Makeup !!! 😱she is a natural beauty💕",
    "THIS is my kind of summer routine. Light and easy! Polished but not cakey!",
    "Her simple routine matches her beautiful skin 💟💟",
    "How easy would life be a if I looked like her😩",
    "She’s so perfect! literally makes me wanna cry!",
    "She’s such a good role model for women. She couldve put on a ton of makeup but she chose not too. Everyone has that same choice whether they are as gorgeous as her or not. It’s about feeling secure about yourself and living simply.",
    "skin is so flawless, wow",
    "finally someone who does makeup like a normal person would",
    "seriosly she is gorgeous and i dont understand when people hate her ♡",
    "How does a successful and busy woman like her not have any dark eye circles T.T",
    "She hardly wore makeup because she already looks like a goddess lol I don’t think this looks is normal people friendly",
    "i really love her outfit it is so pretty and white. she is so charming and beautiful. have a nice day.",
    "So her brows are perfect just like that?..... okay...... so unfair :(",
    "the trick to looking great : genetics",
    "She seems so nervous",
    "i cant understand her beauty",
    "Jesus Christ I’m ugly",
    "step one: be fucking pretty",
    "all these videos are pretentious off the bat, but this is the first one i’ve seen where the featured person isn’t totally obnoxious.",
    "that really wasn’t very helpful?  how about a little more description and specifics?",
    "she is average",
    "so this is the girl who stole my man",
    "i really love her hair. she is so charming and beautiful. her make up tricks are amazing and  wave hair is amazing. have a nice day",
    "She’s so cute and seems genuine. Why is everyone so hateful",
    "I want to see more diverse hair and makeup tutorials, Vogue",
    "This video changed my life honestly forget the curling part but seriously my hair used to be a mess",
    "she’s so crazzzzzzzzzyyy i love her!!",
    "am i the only one who sees her head/face shape as kinda weird?",
    "the people in these comments are such freaks",
    "*Warning*: looks good only if you’re naturally super gorgeous",
    "Love how she puts her bronzer on haha Also that you don’t have to cake make up on like all these makeup youtuber’s and look like a supermodel",
    "She lookss soo cool.. unfortunately my hair is far too thick and straight for those buns and if i wore that eyeshadow Id look suuper sick hahaaha but she looks awesome",
    "this makes me angry... no blending no brushes no highlight no contour NOTHING !",
    "i can not understand eyeshadow that isn’t blended. it’s just sloppy.",
    "she’s so bad at makeup. I love it",
    "I love her energy! 💖💖",
    "She seems like such a sweetheart! ♡",
    "Is glossier better for natural makeup? I want more lighter foundation so I don’t have cakey stuff on all day it makes me so fricken oily. Anyone try it before?",
    "I don’t even know who she is but I really like her 💕",
    "All these girls don’t need a concealer. I canot go anywhere without it. I look sick :(",
    "Only models can can get away with doing the shittiest hair and makeup. As long as you’re skinny you’re gonna be seen as high fashion.",
    "her freckles are absolutely gorgeous!! they suit her face so perfectly. she’s so so pretty and her personality is too. inside and out. she literally makes me feel like i’m on facetime with her.",
    "I love her “don’t fix what’s not broken” mentality! It’s honestly very refreshing to see, especially considering the fact that she works in the modeling industry 😌😌😌",
    "Finally a person who’s bringing out her beauty and not covering it with a bunch of concealer, foundation, contouring etc. Stunning!",
    "Her freckles are so cute. Did anyone else think her lip pigmentation is so unique it literally looks like she has permanent lip liner on.",
    "she’s a real one for saying and showing the product’s names and brands!!! <3",
    "So great to hear a well-spoken person without \"like\" after every other word",
    "I don’t understand what kind of hate she gets , I think those people are just purely jealous, cause she is stunning !!! 😍",
    "I always watch these when I’m doing my skin care :)",
    "That’s one confidant, sweet person! All the best❤️",
    "Love her 🥺🥺🛐🛐🛐🛐",
    "Absolutely gorgeous 😢💗💗💗",
    "Never seen a dark skinned person with so many freckles 😮. She looks gorgeous and quite exotic.",
    "Freckles are beautiful. Gods unique markings",
    "Why is hair oil controversial? 6:48",
    "So lovely to see another celebrity comfortable without using the filter!",
    "I really enjoy her personality. She’s so down to earth and relatable.",
    "Finally. A video where a celeb isn’t pushing their own makeup/beauty line!",
    "Wow she literally looks 17. So pretty and ageless.",
    "I could watch her talk for 5 hours straight",
    "It’s nice to see a Hollywood celeb who seems actually normal and not with their head in the clouds! Also without too much filler/botox etc.",
    "Y♥️U are so adorable & unique🎶 Love that you Love your beautiful eyebrows🥰",
    "Like that eyebrow brush♥️ I posted a video of my make up imagining that I am doing that for Vogue. Maybe one day Vogue would start series and show not celebrity people beauty secrets here🤔",
    "She’s really pretty with or without makeup but her lips is really bothering me 😢😅",
    "I like her as an actress, but she’s kind of boring.",
    "So refreshing to see a celerity who is just talking about products they love and not shilling their own makeup/skincare line.",
    "she embraces all the wrinkles and still looks so youthful and fresh.",
    "This is exactly how women used to do make up; no contouring, no baking, caking, or whatever it’s called, no overlining lips and brows. Just a natural makeup letting your skin breathe.",
    "Someone who really haven’t gotten much procedures done and pass it as their natural look but this one is a real natural faced celebrity who truly tells us products she really loves unlike sponsored products which most celebs promotes",
    "She will be gorgeous forever. A toddler could scribble on her face and I’ll still be in awe.",
    "I appreciate her grace and Beuty. She acknowledges her beauty but also owns her flaws. She doesn’t try to hide them. What a confidence.",
    "She is AMAZING ..Started watching as I was doing my night time routine before bed ..AND SHE TOTALLY INSPIRED ME ..THANK YOU",
    "One of the most talented, beautiful actresses ever. Adore this woman, she’s always been so real",
    "She looks more beautiful now than ever.🙏🏼♥️☮️🌸",
    "Hey sweetie thanks for sharing your personal routine. I exfoliate my face with baking soda about twice a week.",
    "Wonderfully gorgeous! She is definitely a role model to all women.",
    "Nice to see the natural you, not succumbing to the all the plastic surgery of many celebrities (aka Madonna of late , no lines but looking like a plastic alien). You far more beautiful.",
    "GORGEOUS!!! 💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕",
    "Wow, she has huge eye sockets. But very pretty women.",
    "does she smoke? she has severe smoker’s lines.",
    "Her face looks so painful.",
    "I would say you have Botox I can tell you have very little movement in your brow area",
    "“Some people say I look sweaty, it’s just healthy skin babe” that’s so me😭",
    "Bruh, I was dying when she paused in confusion about the shade of her foundation!! \"Not for Vogue!\"🤣 So cute! I can relate, blend that demarcation girl!!",
    "Ive been doing the black eyeliner trick on my upper water line myself since I learned how to do makeup. I too also feel like when you curl your lashes and put on mascara that you see the difference.  🙌🏼❤️✨ love this trick!",
    "She is so outrageously pretty to me that it almost hurts to look at her for too long. What I would give to have just an ounce of her natural beauty and adorable personality to match. \n Also, has anyone here actually tried wearing that Baccarat perfume? The price of such a small bottle makes me want to faint but I hear so much about it and I’m dying to know if it’s worth the price.",
    "she’s so cute, watching her makes me feel comfortable and I do learn some tips too",
    "I hope she’s learned to treat her coworkers better. She needs them as much as they need her for a production to succeed.",
    "Funny when she’s talking about how her current job isn’t about glam they mute her 😂",
    "it cracks me up so much when they fast forward over them talking as they apply products... like how did you decide what they were saying there was unimportant enough it was worth muting 😂",
    "It’s a shame they still give visibility to this woman after everything she’s done!",
    "She is known in the industry as a mean girl.",
    "Why is this series always reading like an infomercial for certain products.",
    "So much respect for this beautiful young woman who honestly looks like the perfect mix of both her parents and has managed to be so strong through everything their family has been through in the past few years. She seems hard working and down to earth and I hope she has a great career ahead of her",
    "She is so stunning ✨ I love how natural she keeps everything 🤍",
    "She’s actually interesting and fun! I just love that she has a nice personality behind the pretty face!",
    "Her parents have raised her so so well 🫶🏼🫶🏼🫶🏼",
    "She is so beautiful on the inside and on the outside. She has such a lovely soul. There are so many great things ahead for this beautiful young lady. I wish her the best ❤️",
    "Wow. I think this is one of the very few Vogue “beauty secret“ videos where a major celebrity is not using a filter or wearing full foundation beforehand. You can see all of her discoloration, her pores and lines. It shows that she’s not afraid to be herself and is still beautiful!",
    "Finally someone who admits they dont take their make up off every night. Some of us have real lives that are so busy that having a fifty step cleanse routine is impossible! She’s so relatable and looks gorgeous.",
    "I absolutely adore her! Sigh...\nI do wish we can get to a place where celebrities can be comfortable enough to let us truly see what they look like. You can definitely see that this was shot using a filter. Everyone does it! This is absolutely no means as a personal attack! I wish that we can all just be. Just exist and be happy in that❤",
    "Love how she admits to not taking her makeup every night. The realness",
    "She’s so effortlessly fun and funny. Watching this makes me feel like we’re close friends and I could just do my makeup alongside her and have a fun chat.",
    "Her face moves so she obviously doesn’t do Botox. She’s very natural and I love how real and humble she and her mom are.",
    "she’s gorgeous and glowing. i wanna buy everything she used in the video LOL",
    "how does it feel to talk about wellness while there are fillers in your whole face..",
    "Love her carefree personality but she better stop with the lip filler or whatever she is doing.",
    "TOO MUCH EDITING! She barely mentions warmer foundation in the middle and lighter at the edges… then you CUT HER OFF! Why does she do that? I can see her talking but you mute it! Why have her here if you’re going to filter the very reason she’s here???",
    "Why are you blurring blemishes on these videos? I see it going in and out on her chin.",
    "The botox and filler is beyond distracting. Enough!",
    "Her energy literally just healed me.",
    "I feel like I’m on FaceTime with my friend watching this ❤ Also she has the perfect energy for a Disney princess",
    "I love her energy and that she is just being her self.",
    "I love her! Have been (loving her) since I was a kid and now I’m in my twenties ❤ she’s so funny and lovable, a true queen!",
    "There’s something about her that’s so accessible. I feel like I know her ❤",
    "She is my new obsession 😍",
    "you are literally the cutest person i’ve ever heard!!!!! love love love <333333",
    "its so refreshing to see someone who doesn’t use Dior or charlotte tilbury on here",
    "Im so happy she didn’t ruin her face with surgery. She looks great.",
    "what a class act.  so down to earth and like nothing even when it’s all of us watching.",
    "She’s so likeable, honest and genuine.  She’s bright and intelligent.  Basically the opposite of GP and goop.  The ritual of it.  That’s definitely me - the ship is sailed - 50years of sun exposure,stress …weight changes and menopause ….but I love my skincare morning and night. Makes me feel special.",
    "She’s just so cool as a person, I only heard her talk as of this year and she’s just so sweet and authentic. Also she looks great, love a queen that prioritizes skincare 💁🏼‍♀️",
    "You and I are the same age and I too love taking care of my skin so when I saw this, I had to stop and listen! Thank you! Adore you! 🥰🥰🥰",
    "A beautiful baby, a charming girl, an amazing teen, and an absolutely fabulous woman 🌹💖",
    "We like to see more male models here.",
    "He’s my biggest inspiration 😭😭 not too many models for us young black men to look up to",
    "its great guys take care of their skin!! please keep male skincare routines coming 😊",
    "I love watching males embrace their beauty. Beauty does NOT have A GENDER! It never has, and never will have one. We need more males on here. Literally for skincare or for the males that do both skincare and makeup.",
    "Its nice to see that more males are doing the skincare videos. I am not a guy but I think that this would help normalize that skincare and makeup is not \“girly\”",
    "I just loveeeeee her personality she seems soooooo chill",
    "It so nice to see someone who also had/has cystic acne and also tried acutane for it to fail too. Makes me feel a lot better about my skin journey since it’s so similar",
    "Love her, she seems so nice and down to earth 💖",
    "Idk if I sound creepy but I really love how she applies skincare products/makeup products with her hands, just swiping under the eyes across her cheeks🥺✨it’s all so soothing to watch",
    "I would totally be friends with her, she seems so chill and humble! Love her",
    "This girl is a person that you should idolized and hype up NOT the kardashians!",
    "Love her! She’s such a beauty! There’s something very ethereal about her, like she could be a forest fairy. She also comes across as genuine and not spoilt. Her mother is very sweet, too, and I think raised her very well.",
    "despite being a nepotism baby, she’s very likable & has a pure, wholesome spirit. she doesn’t come across as spoiled or arrogant, tbh I’m starting to really like her.",
    "Tbh she seems very down to earth and just curious and positive .. 🥰",
    "Everything about this video is just so fresh and light! ♡",
    "Nepotism and privilege is everything! She wouldn’t last a day without her last name. There are tons of stunning and gorgeous hard working models/actors that are struggling to make their name in the industry but people like her just get it all cuz of their parents and the connection.",
    "Dont u wet the cleanser before applying so its dumpy or makes foam??",
    "Which shade fenty gloss did she use?",
    "im so insanely proud of her she’s my all time favorite person ❤️‍🩹❤️‍🩹❤️‍🩹❤️‍🩹❤️‍🩹❤️‍🩹❤️‍🩹❤️‍🩹",
    "she’s so pure i adore her 💘💘",
    "I love it! i belive makeup is so natural, personal and unique to  the individuals face!",
    "I’m so in love w heeeeer, she’s so beautiful inside-out and so mind-blowing talented, can’t wait for so much more of her",
    "my darling looks amazing im super proud of her this truly felt like a facetime <3",
    "I really can’t believe how she’s such a beautiful human being 😭💞",
    "thank u vogue for letting her be on here, my new comfort video <3",
    "I SCREAMED OMGGG I LOVE HER SO MUCHHH ❤",
    "i love her but it hurts me so much seeing such a natural beauty meanwhile i always have to try too hard and then fail...i just wished it was easier for me 2",
    "She is such a strong earth sign vibe...it took me like 90 seconds to guess she must be a Virgo. So yea (:",
    "This is such a big comfort",
    "Why does apply something and keep rubbing it off like?? What’s the point sis..it kept bothering me.",
    "Okay, I love you.",
    "Her skin is so natural and beautiful she’s so pretty ❤️😮",
    "Love to see her in Vogue. She’s so cute and quiet beautiful 😍👌👍",
    "She has beautiful, innocent eyes! 🥺",
    "She so cute and beautiful, proud to be black and African 💪🏾👸👑😘😘",
    "Her contacts are terrifying",
    "I love you 😟I just can’t help it 🤲🥰🥰I have thick eyebrows too and natural dark lips tho I’m thinking of using pink lips balm but I won’t anymore 🙃🙃",
    "Why her pupils so big? looking like a Anime character 🥴",
    "Literally every celebrity is coming out with their own skincare line. Skincare is the new celebrity fragrance.",
    "How she doesn’t get listed as a top 5 most beautiful face is beyond me. It’s so perfectly structured and symmetrical I’m in awe",
    "This is by far the BEST No makeup makeup look I’ve seen.  She is a natural beauty.",
    "Sis hit the genetic lottery, she’s so breathtakingly beautiful!  And feel like she’s a great role model. She’s classy, devoted to her family and never out and involved in drama or nonsense!",
    "Now this is effortless beauty. love her bone structure, freckles, and simple ponytail. I also love that she used a drug store color-correcting pallette to achieve this flawless look. no dramatic contouring and highlighting...just focusing on evening out the skin and accentuating her natural beauty",
    "She’s my favorite 😍 of course she has a skincare line lol",
    "She’s stunning, so pretty, but giiirl, really, all that jewellery and that beautiful shirt while washing, exfoliating, masking, moisturising your skin , I mean, where is the good old bathrobe and a real strong headband, and all that jazz we all need while doing our skincare routine😁 I wish I could be that glamorous during my skincare routine 😂",
    "Nowadays… 99% of these videos are advertisements for new celeb skin care lines and its just unrealistic to expect us to believe what they are saying about their own line.",
    "Hello Everybody life is precious please take this moment and receive God in your life pray to God everyday for his help in life situations, read the holy bible everyday, believe in God more than you believe in anything else",
    "☝🏼WERRK!! \n AHHLLWAYS 👑BEEN GWOR-GEOUS!!\nLOVE HERR!! ⚘💐⚘",
    "This face?? Like how does she look exactly the same without makeup with such even tone, helpppppp",
    "Not even surprised by the comments: why is it any time a woman is on here they talk about the way she’s aged. She obviously looks amazing but Like do y’all focus on anything else other than ppl’s ages.",
    "I love her but she is making so many mistakes!!!! Cleanser, mask then serums. Never put the applicator on the face directly!!! Also do your neck!  She is stunningly beautiful. I feel like there’s too much sit C, What are all the concentrations? I would react so bad! Niacinamide, Vit C and a peptide serum are all you need with a good SPF and moisturiser. Cerave face wash, cheap and amazing.",
    "she’s a natural beauty,she has such great skin and her voice is so soothing",
    "I actually can’t conceptualize being this flawless",
    "She’s so beautiful and her skin’s luminous. When she said she was just going minimal with makeup I didn’t expect a basically full face, though…",
    "Just saw her IG account, and seeing her with a thick womanly figure, GORGEOUS!",
    "Gooorgeous!!!!💖🌟❤️🌟",
    "Why are you blurring the real skin texture vogue?",
    "I love these but wish you all would stop with the heavy facial blur filter. We want to see that models and celebrities have texture too.",
    "shes so cute and aesthetic and soo gorg omggg",
    "What a likeable person she is! No wonder she’s so loved by so many.",
    "Now i see why she became so iconic even though her height or even beauty wasn’t specifically special. It’s her personality. Her aura. She’s not bitter nor boring nor stuck up nor fake. She’s herself and she doesnt take life too serious. She has a youthful jokey fun spirit.",
    "she seems like the sweetest soul and her voice is just so soothing and soft. she was the beauty of the 90s and she’s aged so gracefully and naturally that she still remains as beautiful as a rose, i’ve always admired her and continue to to this very day!",
    "So lovely to see someone who doesn’t feel the need to over embellish their looks. ❤️",
    "I was deeply unprepared for how spectacular her vibe is. So beautiful, so kind, and just lovable. She is sunshine and stars ✨",
    "She is gorgeous. Her make up was so simple. When you’re a natural beauty you don’t need much... she seems healthy too, and peaceful within herself. Lovely spirit.",
    "I mean…she is just the epitome of beauty. Needs absolutely nothing and is stunning. She is sublime",
    "Yes definately love her natural look! it was great watching her do her skincare and make up! xx☺👍🌞🌜💜💜💫💫💫💫🌻🌻",
    "She is still the most beautiful soul in the industry, pure at heart, never fake.",
    "They have the biggest filter on her and most of this is bs like most of these videos are, but she still looks good. Her cheekbones are gorgeous.",
    "I love that she is a minimalist. I hope to see more of this instead of the pancake trend of the past few years.",
    "Her beauty fascinates me😍. I could look at her all day! Lol ❤❤",
    "She literally did no makeup naturally she is so gorgeous 💕💕💕🌸🌸❣️😍😍😍😍😍both inside and out and how she flipped her hair😍😍😍😍😍😍😍😍🌸💕💕💕💖💖💖",
    "I love her she is so good and amazing ♥️♥️♥️♥️♥️♥️💖💕😍😍😍the way she is 😍💕💖💖💖♥️🥰🥰🥰god bless you queen 🥰🥰♥️💖💕💕pure inspiration for young girls out there💕💕💕💕💕",
    "Absolutely insane how’s she’s launching a wellness brand/clean girl image..the irony is astounding",
    "stop i love her so much. her personality is literally everything !!",
    "she’s so talented and such a ray of sunshine, i think she’s going to have a super successful career i love her",
    "I love her. She’s so sweet and adorable. I’m really happy she got to do this video. She’s so talented. I’m really excited to see where her career goes.",
    "yess she slayed she is so beautiful 🥹❤️‍🩹🫶🏻",
    "stop I love her she’s so pretty and she seems so down to earth",
    "she is the sweetest person ever omg <3",
    "Whoever’s reading this, i pray that whatever you’re going through gets better and whatever you’re struggling with or worrying about is going to be fine and that everyone has a fantastic day! Amen",
    "STOPPPPP omg i was not expecting this. i love her 😭",
    "I❤️Vogue…A Force of Fashion!  Vogue gives you an inside look into fashion… sometimes moving pass tradition and international boundaries…everything creative in fashion… Vogue❤️",
    "You look more beautiful and attractive when you smile😭💖",
    "Bye she’s so sweet🥺💕",
    "Never heard of her, but she is pretty :)",
    "I get that’s it’s expression and alllll that. Lot of girls really do wear makeup for themselves. That being said.... it should be a crime to put makeup on a girl this naturally pretty. Like..... if she can’t just walk around like that we are f#<!<3d as a species haha.",
    "Her vibe is like “I gotta pee really bad, but let me tell you this super exciting story first” I love her so much ⭐️❤️⭐️",
    "Queen of literally everything. Stunning, kind, talented, brilliant. LOVE YOU BB❤️",
    "Love her laugh and hear her talk 😭💓",
    "She looks  little bit nervous , but anyways  we stan talented  queen 💖",
    "WE NEVER ASKED FOR IT BUT WE RLLY NEED IT OMG SHE SO CUTE",
    "HOT MAMA I LOVE THIS WOMAN SO MUCH",
    "No wonder her skin is dry if all she’s doing is cleanser then spf. This routine is a mess.",
    "Girl everything is in the wrong order, do your serum, then eye cream followed by moisturizer then SPF 💁‍♀️ but you look great nonetheless!",
    "It would be nice if she would tell us what the products are ... else why watch?    You beautiful, you love the products,  and uh, what are they?",
    "No clue who she is but...man this video was a mess. The order of her products was so wrong. Does she have Ticks...if not it sure seemed like it. She looked beautiful in the end.",
    "Anyone think she’s very high lol?",
    "Is she drunk-?",
    "I love watching her. She has an incredibly pleasant and impressive energy. It’s like watching a close friend of mine.",
    "People so young into skincare.  I knew nothing at her age. She has perfect skin any way though!!❤️❤️",
    "We need to see more celebrities like her with REAL faces. She makes me feel confident and soo much better about myself. She is such a natural beauty 😍",
    "Her skin is flawless. Love her routine and simple products. She doesn’t go overboard with 20 steps of 20 difference random products",
    "Love her especially how she shares her opinions and just isn’t afraid to show her true personality.",
    "Great representation for South Asian women of colour. She is very likable. ❤️ Beautiful clear skin ❤️",
    "She really sounds like a best friend doing her make up while chatting with you. And the fact that she uses eyeshadow for highlights....thank gods I’m not the only one",
    "As a young south asian girl i love to see more representation, she’s so beautiful both inside and out  and someone i look up to ❤️",
    "Just love her personality. Very real, and welcoming.",
    "She looks amazing without any makeup......her smile is so cute....heart melting 😍😍😍😍😍😍😍😍😍",
    "I just love her energy. I wanna bottle it up it take it everywhere with me. Such a beautiful girl inside and out☺️",
    "She’s so gorgeous she gives me really good vibes , she’s like that one classmate that’s friend with everyone",
    "Love the calm and chill vibe - also that eyeshadow. The duality of women.",
    "I really really really really really really really really really really really really really really really really really really really really really really really really really really really love her voice.",
    "This women has my 💕🥹 thank you for sharing all your tips!!",
    "Her moisturizer is 56$. That’s expensive to put on under a wash off mask! If she put the mask first and then her moisturizer and spf, her skin wouldn’t be as dry. I absolutely adore her! She’s absolutely gorgeous",
    "She’s so REAL! Love her natural skin and just sharing small beauty secrets!",
    "This was the best beauty secrets yet! Such a natural beauty.",
    "love this series but my god, you guys have to instruct them to look at the camera and not themselves, it’s so weird to see someone looking to the side all the time",
    "Whats the point of using moisturizer BEFORE masks and then rinse it all off? 🤡🤡🤡🤡🤡🤡🤡",
    "She’s just so naturally funny and never afraid to say the wrong thing and to be vulnerable. She’s the one.",
    "We want more of her doing videos of regular things and saying what she likes and all. She is a beauty 😩😩♥️♥️",
    "she is so unbelievably gorgeous. then to top it off their is her kindness and empathy! incredible",
    "Why am I smiling so hard?!?!? Our girl is just so beautiful and confident!!! It makes me so happy to watch.",
    "She looks like a sweet and honest girl who really took us through her very makeup routine. I learnt some tricks here and there, thanks, queen. ✨",
    "She’s so elegant and down to earth.  Really like her",
    "She just seems so sweet, approachable and genuine. Love this video",
    "She’s so beautiful it should be illegal 😭😍. The way she talks and the topics she chooses always feel so authentic and close to her heart. Love it ❤️",
    "She’s an absolute stunner AND a sweetheart!! 🥹💕💞",
    "Love that her makeup isn’t caked on! Very natural application! Beautiful💗",
    "There is literally no reason to hate this girl",
    "She’s so gorgeous! 🫶🏾✨ it’s refreshing to see her like this, I can’t say I’ve ever seen her in this type of setting! I love it 💕",
    "okay she seems like one of the nicest people everrr! I LOVE HER AND HER ENERGY! Not to mention she is STUNNING♥️",
    "her skin is UNBELIEVABLE. not just in this video but over the years every picture of her I notice her skin. She seems very sweet too.",
    "I could listen to her talking about anything all day, her voice is so calming and I love her personality. It’s almost like listening to a friend instead of a celebrity.",
    "She talks about everybody so positively, her soul is beautiful",
    "She is honest n make everyone comfortable around her 🌸 just love her 😘",
    "So crazy how she grew up before our very eyes.",
    "She’s so natural I love her ❤",
    "I love her, not for popular culture, or for her success she just has something that makes people feel more positive💕",
    "i adore her vibes <3 she is so kind & down to earth :)",
    "I couldn’t stop smiling through this she makes others so happy <3",
    "dude she’s so pretty like omg her eye color is amazing and her lips??? theyre so nice and i can’t believe somebody can naturally have lips that color…like how is she real 😭",
    "Her eyes and lips are perfect, she’s perfection 😍",
    "she is very down to earth and calming and cool and i love her",
    "i love her so much she is just naturally so funny and I feel like I was just with a friend on facetime getting ready together.",
    "It’s so pretty and casual, not all celebrities show off their simple daily routines. 🥰🥰🥰",
    "I don’t know why I just LOVE HER SO MUCH LIKE IN MY HEART SHE IS SO NICE AND FUNNY AND CALMING!!!😭💓",
    "Love her! And omg is she soooo stunning with nothing on her face! ❤❤",
    "She’s so so so so pretty. I dont think she realises she’s that pretty 😭",
    "shes gorgeous with and without makeup",
    "She is so perfect😵‍💫😌✨",
    "Lol her aggressively rubbing her face and happily rubbing a cuticle oil. She’s adorable, like hanging with one of my girls. Her routine is super close to what I do, I just use different products. Super easy if you’re usually in a hurry.",
    "she just amazing nothing less just the best person alive",
    "Love her natural beauty and spontaneity, so fresh this days of fake faces ... I just can’t with every actress having the same lips and nose. She is authentic and incredible beautiful.",
    "It’s amazing at how you take us through the entire makeup phase. Truly amazing",
    "She’s so beautiful!! 💕💕💕",
    "love her energy <3",
    "Thank you Vogue for having a natural red head on your channel 💕",
    "The eyebrow was really nice 👍 love it 😊",
    "omg I love her so much💖",
    "You are a breath of fresh air  😊 💓",
    "Shes stunning but best of all, get personality rocks. She’s seems like such a cool chick that you could hangout with that isn’t fake",
    "Is good to be beautiful",
    "𝑆ℎ𝑒 𝑠𝑜 𝑐𝑢𝑡𝑖𝑒 𝑙𝑜𝑣𝑒 ℎ𝑒𝑟",
    "It’s rare to see men doing beauty secrets on vogue, i liked this! would love to see all kinds of people talking about their doing this beauty secrets series too 😊",
    "I loved her. And I love her even more now. She’s been consistent with expressing her knowledge towards skin care. She’s incorporating it within her line and grew with it over the years. I’m just proud.",
    "I love that she used her own products but didn’t talk about it for 10 mins and just introduced them like all of the other products that she used. I love her so much! What a queen!",
    "Do you guys notice that in every makeup and skincare videos of hers, she is always sharing what she knows and practices, knows exactly what she’s doing and seems to be so enthusiastic about that? Like she really loves these things we can see.",
    "This is the make up routine I did not know how much I needed?! She gave us so many tips! I love the natural make up look and how she tries to enhance her natural features",
    "She is indeed so adorable, kind and authentic.",
    "this poor girl got so hated by the media and public, she seems so sweet and angelic",
    "Love the attention she’s getting. She deserves it 🤍✨🦋",
    "I love love love her honesty. And love that she acknowledges other brands and how to properly use it. Shes so normal in the best way. It’s inspiring",
    "she explains everything so calmly and supports other brands too I love her lowkey vibe💜🍩",
    "She is so pretty, gorgeous and beautiful without makeup, it’s crazy. Her skin is literally ✨goals✨",
    "How can someone hate this woman!? She’s beautiful inside out. ♥️🥺",
    "Her voice is so calm and relaxing 😌🧖🏼‍♀️💗",
    "Love, love.... LOVE her!!! Goddess, icon, queen, beautiful humble human 💖",
    "She’s so naturally feminine and I think that’s what makes her a goddess 💜",
    "she’s just perfect ❤‍🔥💓",
    "[calm music]",
    "im so obsessed with how one of a kind she is. unique beauty",
    "It’s refreshing to see her lovely face! Thank You Vogue!",
    "I would never of thought someone as beautiful as her would have acne scars",
    "🎀What a brilliant transformation.🎀",
    "She’s an icon haha ❤",
    "she reminds me of that sloth in ice age",
    "That took zero talent or skill. And it’s hiddeos.",
    "She has this soothing energy about her. Also, she’s stunning.",
    "she seems like such a gentle person who has a deep and very characteristic personality underneath the sweetness ❤",
    "you can tell that she’s actually been using these products for a while and that she’s not just promoting them like a lot of celebs do. She’s so humble and sweet we need to protect her at all costs",
    "i love her so much she seems so down to earth and isn’t afraid to show natural skin texture and breakouts. she’s so beautiful ❤️",
    "Love her calmness and the fact she prefers looking herself rather that being all glammed up for carpet looks! She’s incredibly beautiful and this minimal makeup look suits her really well!",
    "I love her calm kind energy",
    "She’s just so calm and gentle. I love her sm",
    "She seems so authentic and so real. She has a calming vibe.",
    "She’s just genuine, love her 💖",
    "She has such beautiful bone structure, she’s ageing like a fine wine, so gorgeous inside and out.",
    "It takes so much courage to face everything you’ve gone through and remain standing. You’re setting a beautiful example for so many people.😇",
    "She’s so elegant , truly the type of woman I want to emulate when i grow older 💕✨",
    "I love her down to earth personality. On Instagram she almost always likes or responds to our comments.",
    "This is the first routine I’ve seen here that makes sense 💖 Love it!",
    "One of the most stunning and elegant beauties in this world 🤩💕🌹 Her cheekbones are out of this world.",
    "Love her💘 she looks stunning per usual",
    "She doesn’t look 51..wtf... love her... 💕",
    "Honestly she’s the only  few who I believe are truly down to earth not \“ fake down to earth\” . I love the roles she takes that are of real people. She’s a great actress.",
    "She seems like a genuinely lovely person. She is very relatable.",
    "How in the world did she grow up so sweet, unaffected and genuine?",
    "She is such a natural beauty and I loved this video. It gave off a calming energy and it was short but sweet.",
    "She’s UNREASONABLY naturally beautiful like, one of the most beautiful women I’ve ever seen.",
    "FINALLY she’s getting the recognition she deserves!!!!😍😍😍😍😍😍",
    "she’s so comforting to watch and listen to, everything she does is amazing !!",
    "SHE IS ABSOLUTELY REAL. THE WAY SHE SPEAKS, THE WAY SHE JUST IS, I love her.",
    "I love her personality! She seems so genuine and sweet, also I really appreciated when she spoke about her anxiety! ♥️",
    "she’s gorgeous and seems like a very genuine person. love her.",
    "love love love your earrings 💝💝💝",
    "so you’re telling me she wasn’t wearing any blush/lipstick prior to putting it on? dude she’s extremely gorgeous. hands down naturally pretty it’s so powerful",
    "I am so in love how natural her makeup is! Her eyemake up looks great on her :3 I bet she can pull any makeup looks and I can’t wait to see it 😍😍😍❤️❤️❤️❤️",
    "love love loveee this <33 now we know her secret to having such flawless faux freckles 🌼",
    "she’s such a sweet and genuine person i love her so much 💕💕",
    "she literally looks like a grungy fairy omg I’m obsessed ♡",
    "she is so insanely beautiful I can’t get over it???? her eyes are so mesmerising, I think I’m crushing help",
    "She is an amazing women with a beautiful and optimistic approach to life. Her messages were very meaningful and I wish her the best in life.",
    "Her voice is so soothing. Such a natural beauty. I love her so much💕💫",
    "I love her aesthetic and style 💖💖",
    "She looks just like normal people. No tightened skin no filters no sleeked back hair❤️",
    "This is probably the most realistic vogue tutorial ever. She has so much personality 👑",
    "She is just a breath of fresh air. Super normal , real , genuine. No celebrity BS telling things that they haven’t done themselves. She is genuinely relatable , absolutely love her",
    "I really like her personality. She is so down to earth and humble. Her personality is super natural and bubbly.",
    "the way she normalizes things like facial hair and hyperpigmentation is everything",
    "This was actually like watching a friend do her make up, rather than a celebrity. <3",
    "I love that she LOVES the makeup and doesn’t try to be \“too cool to use makeup\”. She’s so full of passion and I love it",
    "Her voice is so relaxing and she is so talented! I hope she gets more fulfilling and successful opportunities in the future ❤",
    "I love her personality. Shes so real and this video really made me realize how similar we are.",
    "She’s such a beautiful human being I love her !! So well spoken . 😩💞",
    "I like that she acknowledged that clean beauty is not cheap, that she has struggle with her mental health which taking care of yourself is one aspect of self care, and about having balance. It actually surprised me, and she seems genuine.",
    "Love that she still looks like herself- radiant, glowing, REAL skin look!",
    "The way she correctly used make up to ENHANCE her own beauty and did not just follow those random IG trends.",
    "Oh gosshhhh I love her everything about this is amazing! Her honest genuine down to earth energy and her tips !",
    "I enjoyed every second of her routine/process - she’s so compelling.",
    "She’s so nice and relatable. I loved watching this and learning how to look after my own mixed hair ➰👩🏾‍🦱",
    "She is so gorgeous - love her calm vibe ♡",
    "She honestly feels like a breath of fresh air. She’s so relatable and absolutely stunning.",
    "she’s so fresh and fun, her vibe and energy is everything",
    "she’s so adorable 😭 she’s so radiant, i feel like you can’t not be friends with her!",
    "She has such a bubbly personality. No wonder she has already collaborated with half the kpop insudtry already. I wish to have a friend like her.",
    "I love how she’s not fake like other celebrities showing \"14 steps\" for their beauty secret. She’s just so natural & real to people.",
    "I love her so much. She is a girl that everyone wants to be friends with. I swear she DOES NOT need makeup.",
    "I feel like I was just with a friend in the bathroom watching her doing her make up lol",
    "love how real and authentic she is talking about her skin struggles and normalizing it she’s absolutely stunning",
    "She’s so inspirational and charismatic I could hear her talking all day about the most random things 🤍🤍",
    "She is truly an remarkable person , I just love her, the world need more people like her.",
    "She’s so breathtakingly perfect I wonder if she knows that. Her voice, her eyes, her lips, her skin, her personality just everything about her. She’s just so unimaginable",
    "Was so real of her to talk about her struggles keeping up mentally and physically throughout the show. Iconic!!!!!! She’s such a star",
    "She’s absolutely laughing at herself the whole time for the ridiculousness of being on Vogue, and I love it.",
    "her beauty is SO natural OMG",
    "I love her 💖 she’s so natural and beautiful 😍 these eyebrows look so great and natural.",
    "awhh she is actually the sweetest + so so down to earth! :)",
    "This is my first time hearing about this girl. She’s so naturally beautiful and down to earth! Really enjoyed this 😍✨",
    "This is the most down-to-earth make-up tutorial ever💛",
    "she’s a legend she’s an icon and she is the moment",
    "She made the right choice to not mess with her face.  Stunning woman.",
    "No Botox, no fillers, underarm hair! Refreshing, real and rare to see not like those fake celebrities that misrepresent themselves and pretend they’re like that without \“help\”",
    "This is what I call natural: no poses, wrinkles, no waxed armpits and messy hair. She looks great for her age, plus that charisma. ❤️",
    "what an angel 🖤",
    "I wanna give this girl a big hug!! It seems like I’m watching my little sister blossom She deserves every ounce of fame.",
    "shes so humble and sweet and sooooo down to earth, we need more people in Hollywood like her",
    "when she said she used to hate the way she looked I LITERALLY GASPED. she looks like an angel",
    "Not only is she beautiful but she’s smart, talented and the most unproblematic influencer with the kindest soul✨✨✨",
    "Finally a tiktok star who actually deserved to be here",
    "the most unproblematic person ever, so glad to see her here!!! she deserves it 💕💕💕💕",
    "I love the way she speaks. Her voice has so much depth and power but yet is so soothing at the same time. I honestly feel like she is my auntie teaching me how to take care of my skin haha",
    "Her skin looks so fabulous; she doesn’t seem to age!",
    "Now she’s a natural beauty. No nose jobs, no foxy eye lifts, no lip fillers. Just love her vibe",
    "Her whole vibe is so positive and energetic..love her..🥰🥰",
    "I love her confidence, it’s something I want for myself",
    "I love that the fact that she doesn’t use fillers, or had any cosmetic surgeries, pure beauty! 👌🏽",
    "Please feature more older women... it’s a more realistic representation, and prepares many of us for the future. Aging can be graceful, beautiful, elegant ♡ let’s embrace it, not fear it",
    "i really don’t think she’s \"doing too much for vogue\" she seems like the type of person to have a 58-step skincare routine and i mean it in a good way",
    "the routine itself is kinda ridiculous in some parts, but her face without make up looks just phenomenal",
    "Nothing could have prepared me for the amount of masks she was gonna use.",
    "This is the kind of irreverent and creative makeup routine I can relate to and appreciate! 😍",
    "Finally, someone who doesnt have annoyingly long debilitating nails. Just the reasonable length to keep the aesthetic.",
    "She’s so underrated",
    "Vogue doesn’t realize this, but they’re making everyone’s day better.",
    "I AM OBSESSED WITH THIS, definately one of my favorite beauty secrets💗😍",
    "She’s so elegant and calming. It’s such a pleasure to listen to her talk. ✨",
    "She is a down to earth person you rarely see that in Hollywood, she is definitely special",
    "She has such a calming presence... Which only adds to the fact that she’s a super talented and gorgeous woman",
    "its insane to be that nice. this attitude and aura is what we should strive for everyday",
    "I’ve never seen any body wearing a sheet mask that perfectly",
    "who else agrees that she’s glowing she’s so beautiful! 🥺💘",
    "She’s so likeable, and her lip combo is stunning!",
    "One of the most real celebrities out there. It’s hard to find someone like her, she’s really is rare ✨",
    "She has never really given me huge celebrity vibes. She really looks like just any other girl especially without makeup, and has a very familiar and calm energy.",
    "ALSO I LIKE HOW AUTHENTIC AND NATURAL THIS WHOLE VIDEO IS",
    "No one will ever understand how much this woman made me cry.",
    "She has such a natural confidence to her. Not scared of loving herself, fully embracing who she is and complimenting herself out loud. Beautiful exemple of how every women should talk to themselves. I love her",
    "her vibe is EVERYTHING! I LOVE HER EVEN MORE NOW THAT I HAVE A GLIMPSE OF HER PERSONALITY",
    "It’s so refreshing to see a bathroom that isn’t completely marble for once😅",
    "Her face is just perfection. So symmetrical, so balanced, the ratios are just flawless.",
    "I love how open she is about her skin. Makes me feel normal 💕",
    "yes!! this is what we want to see, actual celebrities and not teenagers who dance on tiktok… thanks",
    "She’s such a classy beauty",
    "Honestly she’s literally the definition of elegance and class, I’ve such a crush on her 😍😍😍",
    "I love how she does makeup that enhances her features but doesn’t cover her natural skin <3",
    "My Queen!!! 💗🖤💘✨✨",
    "She seems so down to earth 💗",
    "The contrast of blonde hair and brown eyes is so stunning she looks like a porcelain doll",
    "she’s so calm and down to earth, i like her vibe",
    "He’s such a calm and gentle spirit. So empathetic and down to earth. I could listen to him talk forever!",
    "She’s an icon. It’s not just her face, it’s her whole vibe ✨",
    "my girl doesn’t even need to contour her face, god already did it for her bruh",
    "I think she is one of the most impressive looking people who’ve ever walked the earth.",
    "This is gonna be the most watched routine on vogue cause she is a gem and everyone loves her.",
    "I love how she’s using drugstore makeup in her routine. So down to earth and beautiful!",
    "Wow she’s a natural beauty! PERIODTTT!!!!💚💚💚💚",
    "She‘s so beautiful, sophisticated and elegant! She definitely gives out rich girl vibes haha she is SO pretty",
    "honestly? i have no idea who she is BUT SHE’S BEAUTIFUL AND HAVE SUCH A COOL VIBE AND PERSONALITY!",
    "It is so nice watching a celeb with skin breakout that actually talks about it and shows it.",
    "I am shocked at this woman’s beauty. She is just gorgeous.",
    "I love how much she is positive ! She has a great energy 🤍🤍",
    "She has such kind eyes and seems like a genuinely sweet person",
    "finally, an actual celebrity",
    "her personality really shines through, shes’s the sweetest",
    "I think she is the first celebrity who doesn’t have that boring all-white bathroom",
    "She’s so genuine and laid back.  I want more friends w/ her type of energy",
    "Why do people hate her tho? I see a really nice and chill person here.",
    "she’s so calm, why do other people hate her. -_-",
    "Why do people hate her? She deserves all the success in the world.",
    "She is the epitome of feminine energy!",
    "I like how she has a chill vibe with intelligence cloaked with grace/class. I like her skincare routine.",
    "I love that she is acting her age which is cute and real.",
    "so down to earth, authentic, and well-spoken. im literally praying that she’ll keep this beautiful personality and the music industry wont be a negative influence for her",
    "she’s so down to earth, it’s like she’s just having a chat with her best friends 🥺",
    "I’m in love with her personality omg",
    "Look at all this charisma uniqueness nerve AND talent",
    "This girl really got a cat eye lift and now explains to us how to get the cat eye look with makeup lmfaoo",
    "It’s so weird because her words and phrases are super expressive and filled with joy and emotion, but her face says otherwise. It’s a tad confusing XD",
    "I’m so mesmerized. Like the monotone voice and dead eyes. It’s hypnotizing.",
    "she’s an inspiration, we need more people like her <3",
    "As an autistic person, she inspires me so much to not feel bad with myself, she gives me a lot of happiness and hope. Love her.",
    "Her skin is an example of what NOT to do related to skincare.",
    "Her beauty secrets just should have remained secret ...",
    "Honestly one of the W O R S T skin care routines I’ve seen.",
    "This is probably the first time of me actually seeing the comment section so pure. Everyone here has something good to say abt her. Like we need more influencers like her in the chart .",
    "She seems so genuine, like she’s the girl that says, \"No girl, YOU’RE so pretty!!\"",
    "her feeling proud of herself after doing her eyeliner in just one eye totally melts my heart like she’s so cute",
    "she is literally so nice and humble and chill and the internet legit eats her alive just because she’s gorgeous. envy is such an ugly thing.",
    "If I looked like this I would literally just stare at myself all day",
    "anyone else pretend that they’re doing one of these videos when they’re getting ready?? lol",
    "she’s just so down-to-earth and that’s what makes her deserve all the love.",
    "Her ending note made me tear up she’s so humble and realistic I love her",
    "When she started talking at the end,I started crying. She is literally so sweet.",
    "Her eye shape is so alluring. Such a beautiful girl. So inspiring.",
    "What a stunning woman, her features are fully doll-like!",
    "40 freaking steps and her skin without makeup still looks most gorgeous and clear ever.",
    "She’s such a natural when it comes to explaining what steps she’s doing 💗",
    "I’m literally obsessed with what she is wearing!! She looks like an angel 🤍🤍",
    "She seems like such a fun, cool and down to earth person",
    "That attitude, the energy, the vibe and the youth just mesmerizing. I love her",
    "she’s so naturally gorgeous & so down to earth. love her.",
    "This should have hit a million in the first hour. This is the skin routine we’ve been BEGGING FOR !!",
    "Low key appreciate that she’s pretty honest in the video and doesn’t talk in a fake baby voice or act all sweet and quiet. She’s honest and talks like a regular person... one of a kind 😂",
    "i love how much she supports her sisters, like even using all their products <3 <3",
    "This was so soothing.  A beauty tutorial, meditation, and inspiration all in one.",
    "They are the most adorable, loving, and caring human being.",
    "I don’t think she realizes that she’s a celebrity",
    "She deserves everything and more 😘💗",
    "Her relatable skin pigmentation and mustache upper lip shadow is so real, thanks for showing real women’s faces vogue 🥰❤️",
    "Aw she has such a cute personality. Just makes her even more beautiful.",
    "She is absolutely gorgeous and hasn’t done anything to deserve all the criticism in this comment section. She’s still so young",
    "I’m not even a fan but adore her so much. Such a sweet angel.",
    "she’s not only drop dead gorgeous, she’s also really humble and kind",
    "Her personality is wonderful. More of her!",
    "Her soul is so genuine and pure, she truly has a kind heart and that’s what I love Ab her, I will always love and support her❤️",
    "She’s literally the most genuine woman EVER",
    "i really love her she’s so natural and she has a pure soul 🦋",
    "She is such a down to earth person....the no makeup promotion and the usage of her mothers brush  shows how beautiful her character is ❤️",
    "I love the fact she can break down the patriarchal corporate system while applying eyeliner.",
    "I love how she doesn’t let her job get in the way for her interest in skincare, make-up, and looking glam! Love the bold lip!",
    "All I hear is \“natural\” here, \“natural\” there… C’mon… she is anything but natural.",
    "Vogue- please get celebrities/ models that are going to be transparent and honest for all of our sakes",
    "I wish they openly talked about fillers and other treatments, those are the actual \"secrets\" we want to know",
    "She’s like a real life Bratz",
    "the way shes so gentle with applying all her skincare products😌💅🏽✨✨",
    "I am so proud of her, just to wetness her beautiful journey and see how much people admire her for her beauty, talent and uniqueness make me so happy 🎀🎀🎀🎀🎀🎀",
    "I’m obsessed with a little bit of highlight here",
    "So beautiful, so raw, so authentic. LOVE HER ❤️",
    "Wow! I love her so much ❤ Self love is something precious.",
    "Aww I love her, I’m glad she found the beauty in her natural self💕",
    "If I had her face, I would NEVER USE MAKEUP, she is a total goddess !!",
    "She's humble, sweet and down-to-earth! Such a Taurus energy 💖",
    "Anyone just keeps rewatching this? She’s just so gorgeous I’m trying to take notes😖",
    "Can we talk about her skin?!?! It’s so gorgeous, glowy and flawless💕🌸🌷🌷💕",
    "She is so cool,she is a girl who everyone wants as a friend",
    "I love her! Unlike a lot of celebs, she's not stuck up! She's so funny, and relatable! She's natural and completely herself.",
    "I love how humble she is... Makes us feel she is one of our friends getting ready with us💕",
    "She is literally so naturally pretty, she's the perfect combo of cute and stunning",
    "she’s honestly so so pretty and her personality is so fun",
    "god really took his time creating her, she's drop dead gorgeous",
    "She is honestly one of the cutest most humble people and has such an amazing attitude ❤️❤️",
    "I've said it once and I'll say it again: THIS 👏GIRL👏 IS👏 ICONIC👏",
    "Yaaaay! The queenie's here!!!!🖤🖤🤍🤍🤍🤍🤍🤍💓💓💓💓💓💓💓💓💓💓💓💓 Just take a good look at her guys...her aura's ethereal! Also, I'm literally OBSESSED with her voice!!!💓💓💓💓🖤🤍🤍🤍",
    "Finally a celebrity that has an affordable skin care routine!",
    "I love how she just giggles randomly. Adorable ❤️",
    "I keep coming back to this tutorial. She’s has such a amazing energy!!! And the makeup tips are AMAZING!",
    "Love her sooo much! She and I have very similar tastes w the not wearing lipstick and loving the effortlessly beautiful, but polished look. She seems so humble and down to Earth too 💗💗💗",
    "She's super cool, love seeing people being real. This was a good one!",
    "I love how real she is, she’s gorgeous but she’s not shy about her imperfections",
    "Why is no one talking about her gorgeous lashes",
    "I feel like all these celebrities on vogue do their makeup so questionably and in such a weird way but in the end it somehow comes out flawless",
    "does anyone else pretend to be in one of these vogue videos when getting ready in the morning no just me ok",
    "VOGUE FINALLY LISTED THE NAMES OF THE PRODUCTS IN THE DESCRIPTION YAYAYYAYA",
    "her lashes💯💗💗💗",
    "She literally has the most iconic and amazing face possible anyone could ever have ….literally her bone structure is set in all the right places ….her nose is so nice ….her lips are perfect …..her jawline is perfection 😌",
    "The level of beauty this woman has 😩😍🔥💗",
    "The best makeup video I’ve watched in my life 😍💜🌸 loves this look and will try to recreate it 😍😍😍😍❤️❤️❤️❤️",
    "She's one of those people where you instantly feel genuinely connected to her when she speaks.",
    "I just need a sound byte of her saying, \“Hey, it’s all gonna be alright\” that I could play on my phone whenever I’m feeling down. She’s just good vibes all around.",
    "Cant get over her, she is so legit and authentic!!! love her!",
    "She’s so...ethereal..it’s almost unbelievable.",
    "her voice is what lip gloss would sound like (idk if that made sense but it did in my head lol)",
    "I love how real she is ❤️❤️I love her 👏🏼👏🏼💕💕💕💕💕",
    "Her SKIN Her MAKEUP her PERSONALITY - everything about this video is on point!",
    "Her personality is so contagious, I love it ♥️",
    "its so cute how happy she is about her expensive products. like you can tell she's new to it and appreciates it",
    "Her vibe is just sooo refreshing. Feels like a sister, mom, friend and mentor. 💗☺️✨",
    "I love how real she is. Her boyfriend is laughing in the background, her cat is hanging out. It is nice to see her in her space doing her.",
    "Vogue toturials give me goooood energy to create make up look like them",
    "Did she seriously just say she has big pores. I’m done. Done with life.",
    "Her voice is so calming I love how she speaks 🥰I can watch this over and over she’s beautiful ☺️",
    "I refuse to believe she's real. She is the most beautiful person i've ever seen what the actual heck",
    "She seems like such a nice person, I want to be friends with her!",
    "Her personality is so real I love how “normal” she is despite being a celebrity",
    "The most wrong way to do everything, yet it works and so unbelievably beautiful!!",
    "Finally someone who says they have dark circles and actually has dark circles lmao",
    "i love how she’s not scared to show her dark circles and embraces them. the way she accepts them and shows them off makes my confidence go 📈📈",
    "My favourite of the vogue series! So genuine, realistic and insanely stunning",
    "She’s stunning, and her personality seems so genuine.",
    "Wow I love her, she’s so down to earth and her make up was sooo bomb too",
    "Is it just me or does her vibe give you like that “safe” feeling ?! Idk what it is about her but she makes me feel safe like everything will be okay 😂",
    "she's adorably sweet without coming off stupid or annoying",
    "she's the most relatable compared to the other videos. She gets puffy when she overslept, she doesn't do this everyday, she uses drugstore make-up, she gets foundation stain on her shirt lol.",
    "I love this. It was so realistic. The \"I'll just put a bunch of stuff on my face and blend it and fix it at the end.\"",
    "That was the most stressful tutorial I’ve ever seen 😂 why do I keep watching it over and over?!?!",
    "Love her energy! She seems so down to earth, she's a beautiful person❤❤❤",
    "I love her so much. Such an unproblematic STUNNING queen.",
    "i love her!! she aged beautifully <3",
    "I love these videos so much, I always intend to watch one but end up watching 10😂",
    "She is among a person, who doesn't look gorgeous in first glance, BUT THE MORE YOU KEEP LOOKING THEM They LOOK More BEAUTYFUL.",
    "Her skin is so soft and smooth and 🌺🍥🥛 SKIN GOAAALS GUYS",
    "Her personality is everything! I love her energy 😍😍😍😂😂😂",
    "she actually is naturally quite likable. she reminds me of that friend you can talk openly to because they aren't judgmental",
    "It's awkward but also entertaining to see someone being chaotic so calmly.",
    "i didn’t realize how likable she is her personality is adorable and she seems really intelligent",
    "she is soo cute 😍😍🥰 , so happy u got on vogue💕💕",
    "she just seems like she really has her life together.",
    "Tbh she literally looks like one of those porcelain glass dolls. She's the most down to earth actress and so REAL.❤️",
    "She looks like a princess. It’s refreshing to see some other, different beautiful women, not just those cookie-cutter Instagram models.",
    "I love how much of an artist she is. You can tell she notices little things and has an eye for aesthetics. So cool.",
    "I like her. She's pretty natural and honest, not putting an act or anything. Its just herself. That's cool.",
    "She’s so unique I love it the other makeup tutorials were so dull",
    "I love how she thinks her blemish and her eye bags are cute. That’s a mindset we all should have",
    "i always thought she was kinda shy or standoffish but she’s actually really cute and sweet",
    "Personality, humble, humorous and pretty! A girl’s girl.",
    "I really love how she kept this thing real. Using just one brush for blush and bronzer, using her fingers for neck makeup... It's amazing.",
    "I can listen to her talk alllllllllll day long. She’s such a beautiful person inside and out. Ahhhh I love you girl!!!",
    "I don’t know who she is but i love her personality",
    "I like her personality. She's not annoying like some other celebs.",
    "Thank you for the beauty advices ❤❤!! You face looks so shiny !",
    "She was on her best behavior in this video. I'm very proud of her.",
    "She appears to be relaxed and comfortable within herself.  Her mother and father did an excellent job with her.",
    "I just love that she embraces natural aging. No Botox, just her gorgeous natural skin",
    "\"you know i'm an artist i cry a lot\" -queen of reality",
    "She doesn’t act like I thought she would. She’s so funny 😍",
    "She has such a great personality!",
    "And this, girls, is how to wear makeup in a god-honouring way",
    "She has the most \"Facetune\" smooth skin that i have ever seen.",
    "she has one of the most charming smiles out of the angels!! love her and her personality🥺🥺",
    "she genuinely seems so lovely, why do people hate her so much? ",
    "You can tell that she is genuinely a nice person. Such a rarity nowadays 💖💖💖",
    "Thank you Vogue for featuring real supermodel with genuine and fun personalies.",
    "I love how confident she is and how she doesn’t cover it up!! She is so beautiful and amazing💗💗",
    "She deserves so much love!!! Such a delight to watch. I love her positive spirit, it just transcends ✨✨✨",
    "This girl is naturally pretty , but she has this enchanting charisma that just cranks everything to 10! Amazing!!!",
    "No matter how much you hate her you can't deny she has the most relatable skin problems. Its inspiring",
    "Everything about this look is giving me hottie vibes..the ponytail/color,lashes,eyeshadow..etc YASSSS 😍🥰❤️",
    "Shes so funny and seems like a friendly person",
    "I love how she’s only talking to her reflection and not the camera. 😂",
    "i love that she doesn't take herself so seriously ♥️",
    "Manifesting her aura, her energy, her skin and literally everything🧿",
    "The most beautiful woman. And that voice. Just Divine.",
    "I love her vibe. Everyone has met someone like her. An independent woman on the go who is true to herself and doesn’t take herself too seriously. Not only is she beautiful but she’s easygoing as well. So refreshing",
    "She’s so fun I felt like I was hanging out with her.",
    "An exquisite beauty! love the genuine simplicity and warmness about her, very refreshing.",
    "I love how’s she’s not just doing her make up routine, but giving us a whole show. Giving us life, girl!",
    "She so soft spoken, I love her personality 💕💕",
    "She proves that you can be simultaneously endearingly quirky and totally chic all at the same time.",
    "She’s one of those people that you can tell has been fully loved her entire life. Her energy seems very pure",
    "She’s so laid back! Love her chill personality and the beauty \“hacks\” she shared were fantastic 💕",
    "Love this woman! Her style, her présence , and not only that but that she uses her platform for people with struggles GIRLTALK  👏👏👏👏👏",
    "I love how this isn’t just a grwm but a full on, down to earth informative conversation about skincare.",
    "There’s something about her personality that makes me love her so much more. She seems very honest and kind",
    "When she did the blush hearts I almost cried she is so so so cute",
    "I love how relatable she is, so refreshing. She is a timeless beauty. So classy and elegant!",
    "Wow she's GORGEOUS and i LOVE her energy! I STAN",
    "I freaking love her! She act so natural, anyone agree?",
    "Never heard of her but after watching this and seeing her lovely bubbly personality, I’m a new fan.",
    "Her skin, her hair, her personality. Everything about this girl is beautiful ♥️😍",
    "her cute little \“finished!!\” after removing her face makeup was adorable",
    "SHE IS SO FREAKING NATURAL.",
    "The people that are hating are just jealous. This girl is drop dead gorgeous.",
    "I appreciate that she is actually telling us the product names unlike with most vogue celeb makeup videos",
    "I love her personality and confidence! It's so positive and beautiful",
    "She’s so sweet. I hope the modeling industry doesn’t wreck her sweet personality.",
    "Yeah yeah yeah she's extremely pretty...But can we just talk about her voice? It's so relaxing and so sweet 😊",
    "You cannot hate her. You just can't.",
    "Love her personality. Fun fresh n enthusiastic.",
    "can I just say I love how she told us what every product was (brand and shade/color)!!!",
    "she has that personality that makes you want to be her friend 💛",
    "This video is ridiculous and inspiring at the same time which is about the strangest combination something can get",
    "I don’t understand a word of it, but it gave me life! Love her energy! I’m obsessed. 😻",
    "She has a nice personality. I like her 💛",
    "I like her more that she's talkative and giving it a personal advices.  💗💗",
    "Her personality... The positive vibes you get",
    "Let’s be honest we all have come here more than once 😂💕",
    "A living doll! 😭👑❤️",
    "When your brows, lashes, lips, skin and hair are just naturally gorgeous...the makeup just enhances what’s already there😩💕🌸🌷🌸💕",
    "Imagine being this gorgeous, can’t relate",
    "She looks so calm and humble 💗😮",
    "Loved how she warmed up through the vid. She’s got a good vibe",
    "her voice is so soothing😩💕",
    "I can NEVER get enough of beauty secrets videos they are so nice and relaxing to watch and i always learn something new :)",
    "It's like she's creating a piece of art rather than simply doing her makeup.",
    "I appreciate that she gives instruction on her application and is willing to share the tips she's learnt. She was once on my flight and she is naturally stunning.",
    "I like how she was just genuinely showing us her beauty routine and not just obnoxiously advertising her brand. She is so likable and beautiful.",
    "This woman just makes me ridiculously happy for some reason. There's something so positive about her.",
    "Her skin is clearer than my future....",
    "Ugh!! Her skin looks stunning!! Total Beauty goals.✨✨",
    "Omg I love her personality ✨ she should do more videos",
    "She’s so beautiful and has a great personality 😊💕",
    "You are what they call a natural beauty & lets be real, your lashes go on for dayyyyzzzzz!!! Love this look, PLEASE do more tutorials!! In your spare time haha",
    "Can we just to a second to say that her lips look sooooo good! I love the color!!!!💖💋",
    "She is so beautiful and feminine! Wow.",
    "I really like her, she seems nice, friendly, she looks georgeous and like a total powerwoman:)",
    "She looks the bomb 💣 true legend, nobody can top her 😘😘😘😍😍😍💞💞💞",
    "Her face is legit glowing from within! So gorgeous!",
    "How.The fuck.She.Looks.So.Stunning",
    "I really love her skin 🌸",
    "A model with a realistic makeup routine, not trying to be overly goofy and also doesn't show she is eating fast food and sweets?! Whoa I love her <3",
    "She is beyond stunning and unique. Also very youthful looking. I love how her eyes are wide set. 😍",
    "Her beauty is unreal",
    "She has such a sparkling personality. I really like her natural make-up and I really enjoyed this video.",
    "She truly has an exotic and unique beauty. To me, she's one of the most beautiful women on earth right now",
    "She's so underrated",
    "okay, this is gonna sound kinda weird. but i REALLY want her eye shape",
    "She has such a refreshing personality 😊",
    "Damn, she's gorgeous and has a fun personalty.",
    "she’s literally so pretty and funny I’m crying",
    "I love how gentle she is! So calming and soothing❤️❤️❤️",
    "In the entire video I  couldn't stop looking at her eyes ... they're so piercing and beautiful... what a gorgeous woman",
    "this look is perfect! so natural and effortless, love her",
    "she's so stunning, im so proud of her ♡",
    "I manifest that everyone that sees this comment is this beautiful when they are older. <3",
    "Sometimes people forget that she's a human too, with a heart, soul and feelings. Stop calling her ugly. Respect yourself and others enough to show humanity.",
    "Will no-one mention how attractive her voice is, like wow. Can a person fall inlove with that voice, yes yes they can",
    "She’s always been so normal and genuine for being a celebrity ❤️",
    "This is adorable. she's so charismatic!!",
    "i live for the \"beauty secrets\"series<3 <3 no idea why, simply obsessed",
    "She's an absolute ICON!!!! I adore people who embrace and enhance their natural/unconventional beauty- not looking like IG clones !!!! 💯❣‼️‼️❣❣🥰🥰",
    "I have to say. Hers is the REALEST make up tutorial with actual tips compared to some dumb models and celebrities.",
    "dunno why people hate her, she seems pretty nice to me!",
    "she's so chill yet effortlessly stunning. love her!!!",
    "She already has flawless skin before the makeup she doesn’t even need it !!",
    "god i just love her so much",
    "she has such a cute bubbly personality and it makes me smile so much i literally love her 😭",
    "Love it! This feels so real!",
    "dont know who she is but love her style and personality!",
    "I will never, ever understand why and how people think she is ugly or unattractive. Her beauty to me is so elegant and sophisticated yet mysterious.",
    "I don't care if she is natural or not. She's one of the most beautiful women out there!",
    "lol imagine being so rich you can use the hydrating mist like air freshener",
    "She seems like such a cool girl",
    "She's a masterpiece",
    "She is so effortlessly stunning ❤️",
    "*Warning*: looks good only if you're naturally super gorgeous",
    "love how she did it herself, and not some celebrity hair stylist! Makes it seem more achievable.",
    "How can someone look so good without makeup?",
    "How easy would life be a if I looked like her😩"
];


